ray-on-gke/platform/modules/gke_autopilot/output.tf
Cluster CA certificate is public and not sensitive. Fixed a typo.
=> Remove sensitive from cluster_certificate in output.tf

ray-on-gke/README.md
Updated cd command step in ray-on-gke README.md from User section to be more clear coming from the Platform steps.
=> nit on terraform User first step

ray-on-gke/example_notebooks/gpt-j-online.ipynb, ray-on-gke/example_notebooks/ray_basic.ipynb, ray-on-gke/example_notebooks/ray_mnist.ipynb, ray-on-gke/example_notebooks/stable_diffusion.ipynb, ray-on-gke/user/modules/kuberay/kuberay-tpu-values.yaml, ray-on-gke/user/modules/kuberay/kuberay-values.yaml
Update the ray image in the kuberay config to the latest version (2.6.1).
=> Update ray image in kuberay config to latest version (2.6.1)

ray-on-gke/cloudbuild.yaml
add cloudbuild.yaml for testing tf template e2e function. Will config github to trigger running on PR.
=> add cloudbuild.yaml for ray-on-gke tf template

dcgm-on-gke/grafana/gke-dcgm-grafana-dashboard.json, dcgm-on-gke/grafana/grafana.yml, dcgm-on-gke/grafana/proxy/Dockerfile, dcgm-on-gke/grafana/proxy/README.md, dcgm-on-gke/grafana/proxy/attempt-register-vm-on-proxy.sh, dcgm-on-gke/grafana/proxy/get_proxy_url.py, dcgm-on-gke/grafana/proxy/get_proxy_url_test.py, dcgm-on-gke/grafana/proxy/requirements.txt
and the grafana configs will be used our blog post in https://cloud.google.com/blog/products/containers-kubernetes/monitoring-gpu-workloads-on-gke-with-nvidia-data-center-gpu-manager
=> Copy grafana configs from https://github.com/suffiank/

jupyter-on-gke/README.md
=> Fix Jupyterhub readme

indexed-job/Dockerfile, indexed-job/README.md, indexed-job/mnist.py
Distributed ML training on GPUs using Indexed Jobs on GKE.
I tested the steps in this guide manually and confirmed they work as expected.
cc @ahg-g
=> Distributed ML training on GPUs using Indexed Jobs on GKE

saxml-on-gke/httpserver/Dockerfile.http, saxml-on-gke/httpserver/README.md, saxml-on-gke/httpserver/http_server.py
Adding the http server source code and Dockerfile for inferencing with Saxml.
=> Add userguide for HTTP server and Saxml

jupyter-on-gke/authentication/README.MD, jupyter-on-gke/authentication/authenticator/gcpiapjwtauthenticator/__init__.py, jupyter-on-gke/authentication/authenticator/gcpiapjwtauthenticator/gcpiapjwtauthenticator.py, jupyter-on-gke/authentication/authenticator/gcpiapjwtauthenticator/gcpiapjwtauthenticator_test.py, jupyter-on-gke/authentication/authenticator/setup.py, jupyter-on-gke/authentication/docker_image/Dockerfile, jupyter-on-gke/authentication/docker_image/cloudbuild.yaml
This PR adds the authentication class the the docker images for Jupyterhub Authentication.
=> Adding Authentication class and docker image

jupyter-on-gke/iap_module/deployments/backend-config.yaml, jupyter-on-gke/iap_module/deployments/managed-cert.yaml, jupyter-on-gke/iap_module/deployments/static-ingress.yaml, jupyter-on-gke/jupyter_config/config-selfauth.yaml
This adds the config and deployments that Jupyterhub will use for auth.
=> Add deployments and auth config needed for IAP on Jupyterhub 

ray-on-gke/cloudbuild.yaml, ray-on-gke/example_ray_job_scripts/ray_job.py
- add ray job submit command in the script 
- add new folder `example_ray_job_scripts` under `ray-on-gke` for test ray python file
=> [cloudbuild] add ray api call

jupyter-on-gke/README.md, jupyter-on-gke/iap_module/iap.tf, jupyter-on-gke/iap_module/output.tf, jupyter-on-gke/iap_module/variables.tf, jupyter-on-gke/iap_module/versions.tf, jupyter-on-gke/jupyter_config/config-selfauth.yaml, jupyter-on-gke/jupyterhub.tf
Currently IAP is not enabled. Once everything is in, I'm going to run through everything again with any new changes and then enable it.
=> Add terraform files and resources for IAP

gke-platform/README.md, jupyter-on-gke/README.md, jupyter-on-gke/authentication/README.MD, jupyter-on-gke/authentication/docker_image/cloudbuild.yaml, ray-on-gke/README.md
Updated the installation guide for Auth. Updated the note about the .tfstate files. Updated cloudbuild README
=> README updates and cloudbuild file change

jupyter-on-gke/README.md, jupyter-on-gke/iap_module/iap.tf, jupyter-on-gke/iap_module/variables.tf, jupyter-on-gke/jupyterhub.tf, jupyter-on-gke/variables.tf
Auth will now automatically create OAuth client so that users don't have to create them.
=> Add automatic oauth client creation

ray-on-gke/example_notebooks/ray-fine-tune-hugging-face.ipynb
https://github.com/huggingface/notebooks/blob/6ca682955173cc9d36ffa431ddda505a048cbe80/examples/text_classification.ipynb
=> Example notebook based on a fine-tuning hugging face transformers model.

ray-on-gke/raytrain-examples/raytrain-with-gcsfusecsi/README.md
Followup to https://github.com/GoogleCloudPlatform/ai-on-gke/pull/87
=> Fix links in RayTrain readme

jupyter-on-gke/README.md, jupyter-on-gke/jupyterhub.tf
Minor things like url fixes, formatting, and descriptions for tf resources.
=> Minor url link fix and resource information

gke-disk-image-builder/README.md
Add more details to the README file and modify part of the documentation to help the reader follow the information and run commands more easily.
=> Make the documentation more clear and easier to follow.

gke-disk-image-builder/script/startup.sh
Sometimes the `ctr snapshot view` command will silently fail (succeed without creating the snapshot). Adding retry around the view logic
See the following log for the repro and how this change fixed it. Look for "Failed to get mount point " and "retry"
```
Nov 15 01:31:49 debian google_metadata_script_runner[833]: startup-script-url: ctr: snapshot tmp_sha256:203226d708244adf6c392a28e22e3a7e276270da43094205137c404fc9949691 does not exist: not found
Nov 15 01:31:49 debian google_metadata_script_runner[833]: startup-script-url: Failed to get mount point for tmp_sha256:203226d708244adf6c392a28e22e3a7e276270da43094205137c404fc9949691. Will retry. 5 retries left.
Nov 15 01:31:49 debian google_metadata_script_runner[833]: startup-script-url: All snapshots:
Nov 15 01:31:49 debian …
```
=> Add retry for ctr snapshot view

ray-on-gke/kuberay-tpu-webhook/main.go
Per @allenwang28, the TPU_NAME and TPU_WORKER_ID environment variables are used for single-host TPUs and can be set using the mutating admission webhook. Therefore, we should change the webhook to inject these vars for both single-host and multi-host TPUs.
Environment vars used here:
https://github.com/ray-project/ray/blob/master/python/ray/_private/accelerators/tpu.py#L14-L1](https://github.com/ray-project/ray/blob/master/python/ray/_private/accelerators/tpu.py#L14-L16)
=> Inject TPU_NAME and TPU_WORKER_ID to single-host TPUs

gke-disk-image-builder/README.md, gke-disk-image-builder/cli/main.go, gke-disk-image-builder/imager.go
=> Support attaching labels to the created disk image.

gke-dws-examples/kueue-manifests.yaml
The new version of Kueue includes retries on Failure https://github.com/kubernetes-sigs/kueue/pull/1595
=> Upgrade Kueue version for DWS integration

ray-on-gke/kuberay-tpu-webhook/main.go
We'll want to be able to configure the port/addr that the webhook uses when running in different environments. This patch adds a `--bind-address` flag that defaults to :443 to configure the bind address.
Looks like some gofmt fixes were picked up as well.
=> Allow kuberay tpu webhook address to be configured

ray-on-gke/kuberay-tpu-webhook/main.go
This commit adds flags --ca-cert, --server-cert, and --server-key. Only the server cert and key are used to serve TLS for now.
=> Add TLS cert args to TPU webhook

saxml-on-gke/httpserver/Dockerfile.http, saxml-on-gke/httpserver/requirements-build.txt, saxml-on-gke/httpserver/requirements.txt
Reduced the image from ~2GB to 126.8MB
=> Cleaned up saxml http server container image

saxml-on-gke/httpserver/Dockerfile.http, saxml-on-gke/httpserver/README.md, saxml-on-gke/httpserver/http_server.py, saxml-on-gke/httpserver/requirements-build.txt, saxml-on-gke/single-host-inference/gptj/README.md
@arueth is doing validation on this
=> add updated server and fix typos

saxml-on-gke/httpserver/README.md
Can be viewed here: https://github.com/GoogleCloudPlatform/ai-on-gke/blob/rueth-saxml-httpserver-docs/saxml-on-gke/httpserver/README.md
=> Added additional documentation on APIs

gke-batch-refarch/01_gke/main.tf, gke-batch-refarch/01_gke/providers.tf, gke-batch-refarch/01_gke/variables.tf, gke-batch-refarch/Dockerfile
=> [GKE Batch RefArch] Updating Terraform providers for google, google-beta and kubernetes.

gke-batch-refarch/01_gke/main.tf, gke-batch-refarch/cloudbuild-create.yaml, gke-batch-refarch/cloudbuild-destroy.yaml
Fixes #208: Updated kaniko-project/executor to v1.20.1-slim
=> Fixes #208: Updated kaniko-project/executor to v1.20.1-slim

applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb
--force is needed, otherwise it uses the cached dataset and the /data folder does not work as expected
=> Fix extraneous bracket in notebook

applications/rag/main.tf, applications/rag/variables.tf, applications/rag/workloads.tfvars, applications/ray/main.tf, applications/ray/variables.tf, applications/ray/workloads.tfvars, modules/kuberay-monitoring/main.tf, modules/kuberay-monitoring/variables.tf
Add option to enable or disable grafana for the ray dashboard. Enabling requires anonymous access
=> Add option to enable/disable Grafana for Ray dashboard

applications/jupyter/README.md, applications/jupyter/main.tf, applications/jupyter/variables.tf, applications/jupyter/workloads.tfvars, applications/rag/main.tf, applications/rag/variables.tf, applications/rag/workloads.tfvars, modules/jupyter/authentication/authenticator/gcpiapjwtauthenticator/gcpiapjwtauthenticator.py, modules/jupyter/authentication/authenticator/setup.py, modules/jupyter/jupyter_config/config-selfauth.yaml, modules/jupyter/main.tf, modules/jupyter/variables.tf
Design doc: https://docs.google.com/document/d/1aubk94Pd6qt1G2B2e-awOQ2ranzwgnSLikj5I6fBUwY/edit?resourcekey=0-2d-BsBiGOkwWrGb5aDYDTg&tab=t.0
1. Change the authenticator to auto fetch the backend service
2. add related permissions
3. changed permission and allow list to type list(string)
Tested-by: zlq
Tested:
Sandbox
=> Improve IAP setup process

modules/jupyter/jupyter_config/config-selfauth.yaml
Config reference: https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-extralabels
=> add extraLabels to jupyter config

applications/rag/frontend/main.tf
Missing env and permission after we migrate to gke cluster. Tested-by: zlq
Tested:
Sandbox
=> Fix DLP filter

modules/jupyter/authentication/docker_image/Dockerfile
Tested-by: zlq
Tested:
Sandbox
=> Update the direction for authenticator to main branch

applications/jupyter/main.tf, applications/jupyter/variables.tf, applications/jupyter/workloads-auto-create-brand.example.tfvars, applications/jupyter/workloads-existing-brand-auto-create-client.example.tfvars, applications/jupyter/workloads-existing-brand-existing-client.example copy.tfvars, applications/jupyter/workloads-without-iap.example.tfvars, applications/jupyter/workloads.tfvars, applications/rag/main.tf, applications/rag/variables.tf, applications/rag/workloads.tfvars, modules/jupyter/main.tf, modules/jupyter/variables.tf, modules/jupyter_iap/iap.tf, modules/jupyter_iap/variables.tf
k8s ingress should be named as proxy-public
backend service for now name it as iap-config-default
Tested-by: zlq
Tested:
Sandbox
=> Fix the naming mess for IAP.

modules/jupyter/main.tf
Reverts GoogleCloudPlatform/ai-on-gke#232
=> Revert "modules/jupyter: fix add_auth"

applications/jupyter/workloads-auto-create-brand.example.tfvars, applications/jupyter/workloads-existing-brand-auto-create-client.example.tfvars, applications/jupyter/workloads-existing-brand-existing-client.example copy.tfvars, applications/jupyter/workloads-without-iap.example.tfvars, applications/jupyter/workloads.tfvars, applications/rag/main.tf, applications/ray/main.tf, applications/ray/variables.tf, cloudbuild.yaml, infrastructure/tfvars_tests/standard-gke-public.platform.tfvars, modules/jupyter/tests/change_jupyter_config.py, modules/kuberay-cluster/kuberay-gpu-values.yaml, modules/kuberay-cluster/kuberay.tf, modules/kuberay-cluster/variables.tf
We recently refactored a bunch of terraform modules but the cloudbuild configuration was not updated. This PR gets cloudbuild presubmits passing again
=> get cloudbuild presubmit passing again

tpu-provisioner/internal/cloud/gke.go
We had auto-repair disabled during testing, we need to re-enable it.
cc @nstogner
=> [TPU Provisioner] Enable auto-repair for TPU node pools

applications/rag/frontend/outputs.tf, applications/rag/frontend/versions.tf, applications/rag/main.tf, applications/rag/variables.tf, infrastructure/outputs.tf
Missing  parantheses due to merge conflict
=> Fix rag app

applications/rag/frontend/container/main.py, applications/rag/frontend/container/rai/dlp_filter.py, applications/rag/frontend/container/rai/nlp_filter.py, applications/rag/frontend/container/static/script.js, applications/rag/frontend/container/static/styles.css, applications/rag/frontend/container/templates/index.html, applications/rag/workloads.tfvars
https://cloud.google.com/natural-language/docs/moderating-text
Detect inappropriate response
Tested-by: zlq
=> Nlp filter

applications/rag/README.md, applications/rag/variables.tf, applications/rag/workloads.tfvars, modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
Additionally:
- Add sane default for Jupyter support email
- Sync Jupyter Autopilot config with https://github.com/GoogleCloudPlatform/ai-on-gke/pull/259
=> Fix rag README and dependent modules

infrastructure/platform.tfvars
- us-central1-a tends to have more capacity
=> Update default zones for L4/T4 nodes

applications/rag/main.tf, modules/cloudsql/outputs.tf
- specify implict cloudsql dependency using module outputs
=> Update frontend dependency with cloudsql

applications/jupyter/main.tf, applications/rag/frontend/main.tf, applications/rag/frontend/outputs.tf, applications/rag/main.tf, modules/iap/iap.tf, modules/iap/outputs.tf, modules/iap/variables.tf, modules/jupyter/main.tf, modules/jupyter/outputs.tf
Refactor IAP module
Tested-by: zlq on AP cluster and standard
=> Refactor IAP

applications/jupyter/main.tf, applications/jupyter/metadata.display.yaml, applications/jupyter/metadata.yaml, applications/jupyter/variables.tf, applications/jupyter/workloads-auto-create-brand.example.tfvars, applications/jupyter/workloads-existing-brand-auto-create-client.example.tfvars, applications/jupyter/workloads-existing-brand-existing-client.example.tfvars, applications/jupyter/workloads-without-iap.example.tfvars, applications/jupyter/workloads.tfvars, applications/rag/main.tf, applications/rag/metadata.display.yaml, applications/rag/metadata.yaml, applications/rag/variables.tf, applications/ray/main.tf, applications/ray/metadata.display.yaml, applications/ray/metadata.yaml, applications/ray/variables.tf, applications/ray/workloads.tfvars, cloudbuild.yaml, modules/kuberay-cluster/kuberay.tf, modules/kuberay-cluster/variables.tf, modules/kuberay-operator/kuberay.tf
- enhance marketplace UI
- support cluster creation with ray and jupyter
=> Marketplace UI updates and support cluster creation for ray and jupyter

applications/rag/frontend/main.tf
NLP fully is enabled
Tested-by: zlq on sandbox
=> Update image to contains the new change for NLP

applications/rag/frontend/main.tf, modules/iap/charts/iap/templates/backend-config.yaml, modules/iap/iap.tf, modules/jupyter/main.tf
Make it more general. Prepare for ray dash board
Tested-by: zlq
=> Move the annotation to IAP

applications/ray/kuberay-tpu-webhook/main.go
Creates a `corev1.Affinity` object if the field is missing from the Pod spec in order to inject podAffinity. Manually tested by creating a RayCluster with both `affinity: {}` and the field missing, verifying that the pods are created successfully, and checking that all env vars, labels, and podAffinity values are injected.
=> Fix broken podAffinity path for non-helm yaml

applications/rag/variables.tf, cloudbuild.yaml
- fix sql table_name default value for marketplace
- fix cloudbuild yaml timeout to 90m
=> fix sql table fix for marketplace & increase testcases timeout

applications/rag/frontend/README.md
1. Remove Cloud run related information.
2. Add detailed description for DLP and NLP
=> Update frontend README

applications/rag/README.md
Incorrect indentation causes code blocks to be used for plain text.
=> Fix README indentation

applications/rag/variables.tf, modules/kuberay-cluster/main.tf
=> Remove T4 nodepool for RAG

applications/rag/frontend/container/main.py, applications/rag/frontend/container/rai/nlp_filter.py, applications/rag/frontend/container/static/script.js, applications/rag/frontend/container/static/styles.css, applications/rag/frontend/container/templates/index.html
1. check on the highest value from NLP
2. improve DLP title
3. Range bar will change color and have value showed
Tested-by: zlq on local
=> Update Frontend UI

applications/rag/frontend/container/main.py, applications/rag/frontend/container/static/script.js
=> Get backend server error message

cloudbuild.yaml
tf destroy needs to have same variables as tf apply
=> CI hotfix: fix rag destroy step 

applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb
1. Use Netflix data set
2. Pined version
3. Add time counter
Tested-by: zlq
=> Switch to Netflix data set

applications/jupyter/main.tf, applications/jupyter/metadata.display.yaml, applications/jupyter/outputs.tf, applications/rag/main.tf, applications/rag/metadata.display.yaml, applications/rag/outputs.tf
- Update jupyter outputs to port-forwarding page
- update MP suggestedNext Steps
=> Update  jupyter outputs to  default to port-forwarding

modules/jupyter/authentication/authenticator/setup.py, modules/jupyter/authentication/docker_image/Dockerfile
upgrade some of the versions for the authenticator image. This should decrease the number of vulns
=> Upgrade version of dependencies for authentication. 

modules/kuberay-operator/kuberay-operator-autopilot-values.yaml, modules/kuberay-operator/kuberay-operator-values.yaml
Based on https://github.com/ray-project/kuberay/pull/1896
=> Add securitycontext to kuberay operator

modules/kuberay-cluster/main.tf
* Add Ray client port (10001)
* Only apply external ingress ports to Ray head
=> Network policy cleanup

applications/jupyter/README.md, applications/jupyter/metadata.display.yaml, applications/jupyter/metadata.yaml, applications/jupyter/profiles.md, applications/jupyter/variable_definitions.md, applications/jupyter/workloads-auto-create-brand.example.tfvars, applications/jupyter/workloads-existing-brand-auto-create-client.example.tfvars, applications/jupyter/workloads-existing-brand-existing-client.example.tfvars, applications/jupyter/workloads-without-iap.example.tfvars, applications/jupyter/workloads.tfvars, applications/rag/README.md, applications/rag/main.tf, applications/rag/metadata.display.yaml, applications/ray/TPU_guide.md, applications/ray/metadata.display.yaml, applications/ray/metadata.yaml, cloudbuild.yaml, modules/jupyter/authentication/README.MD, modules/jupyter/authentication/authenticator/gcpiapjwtauthenticator/gcpiapjwtauthenticator.py, modules/jupyter/tests/test_hub.py
- fix marketplace description
- fix sql instance name with prefix
- Rename Jupyterhub to JupyterHub
=> fix marketplace description & sql name

applications/rag/frontend/container/main.py
Frontend will not break when 
- Database not generated 
- Database return empty result
=> Catch Frontend DatabaseError

applications/rag/frontend/main.tf
consume the latest change
Tested-by: No test
=> Update frontend image

applications/rag/README.md, applications/rag/metadata.display.yaml, applications/rag/outputs.tf, modules/kuberay-cluster/outputs.tf
update instructions on how to enable IAP
add ip address output for ray dashboard
=> update instructions on how to enable IAP with an actual domain

applications/rag/workloads.tfvars, infrastructure/main.tf, infrastructure/platform.tfvars, modules/gke-autopilot-private-cluster/main.tf, modules/gke-standard-private-cluster/main.tf
- Fix data source block for subnet for private gke module
- add private_cluster flag in RAG workloads.tfvard
=> fix infra private cloud

applications/rag/README.md, applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb, applications/rag/workloads.tfvars
- Remove unnecessary expensive pip installs from notebook
- Fix table name in notebook
- Clean up README
- Simplify workloads.tfvars
=> Update README & simplify workloads.tfvars for RAG

applications/jupyter/metadata.display.yaml, applications/jupyter/metadata.yaml, applications/jupyter/outputs.tf, applications/ray/metadata.display.yaml, applications/ray/metadata.yaml, applications/ray/outputs.tf
- expose namespace name as terraform ouput and marketplace outputs.
=> support output namespace field

applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb, applications/rag/example_notebooks/ray-hf-cloudsql-latest.ipynb
Fixes an issue with the ray client when trying to retrieve job status.
=> Use ray[default] package in RAG notebook

benchmarks/infra/stage-1/modules/gke-infra/cluster.tf, benchmarks/infra/stage-1/modules/gke-infra/main.tf
Scoped to infra stage-1 for now.
Will do follow up PRs for any other source modules in other stages.
Avoid breaking changes to main dev branch as experienced with the recent default node pool:
ref:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2182
=> add versions to source modules

benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-master-controller.yaml.tpl, benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-worker-controller.yaml.tpl, benchmarks/benchmark/tools/locust-load-inference/runner-manifest-template/locust-runner.yaml.tftpl, benchmarks/inference-server/text-generation-inference/manifest-templates/text-generation-inference.tftpl, benchmarks/inference-server/triton/manifest-templates/triton-tensorrtllm-inference-docker.tftpl, benchmarks/inference-server/triton/manifest-templates/triton-tensorrtllm-inference-gs.tftpl
This change adds labels to identify the specific model, inference server and the source of the yaml file.
=> Add model, inference server and source identifiers

applications/jupyter/metadata.display.yaml, applications/jupyter/metadata.yaml, applications/rag/metadata.display.yaml, applications/ray/metadata.display.yaml
- Hide out the options to choose exisitint GKE clusters and always create new cluster
=> hide existing cluster from MP

applications/jupyter/main.tf, applications/jupyter/metadata.yaml, applications/jupyter/outputs.tf, applications/rag/main.tf, applications/rag/metadata.yaml, applications/rag/outputs.tf, applications/ray/main.tf, applications/ray/metadata.yaml, applications/ray/outputs.tf
Add deployment name as prefix to clustername in marketplace deployment
=> add deployment name prefix for cluster_name in MP

modules/iap/iap.tf
- Add checks that will fail fast, if domain and member_allowlist are empty..
=> Add Validation for IAP domain and allowlist

modules/iap/iap.tf
Reverts GoogleCloudPlatform/ai-on-gke#542
Allowlist check is broken
=> Revert "Add Validation for IAP domain and allowlist"

tutorials-and-examples/tpu-examples/single-host-inference/jax/stable-diffusion/export_stable_diffusion_model.py, tutorials-and-examples/tpu-examples/single-host-inference/jax/stable-diffusion/install-stable-diffusion.yaml, tutorials-and-examples/tpu-examples/single-host-inference/jax/stable-diffusion/serve-stable-diffusion-tpu-v4.yaml, tutorials-and-examples/tpu-examples/single-host-inference/jax/stable-diffusion/serve-stable-diffusion-v5e.yaml, tutorials-and-examples/tpu-examples/single-host-inference/jax/stable-diffusion/serve-stable-diffusion.yaml
The old dependencies don't work anymore. Make the necessary updates to fix the errors.
=> [FIX] Update scripts to make TPU example work 

applications/rag/README.md
Document https://github.com/GoogleCloudPlatform/ai-on-gke/issues/565 and solution.
=> Document known issue with Cloud DNS

best-practices/ml-platform/examples/platform/sandbox/README.md
This PR should fix some errors encountered during the sandbox deployment, and add some clarifications in the README.md
=> Fix sandbox deployment

applications/jupyter/README.md, applications/rag/README.md
=> Add troubleshooting for when a loadbalancer org policy forbids external https, impacting IAP

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/run.sh, benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py, benchmarks/benchmark/tools/locust-load-inference/locust-runner/app/data_model.py, benchmarks/benchmark/tools/locust-load-inference/locust-runner/app/main.py, benchmarks/benchmark/tools/locust-load-inference/main.tf, benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-master-controller.yaml.tpl, benchmarks/benchmark/tools/locust-load-inference/runner-manifest-template/locust-runner.yaml.tftpl, benchmarks/benchmark/tools/locust-load-inference/variables.tf
In addition to Jetstream support:
- Made --stop-timeout an opt-in variable
- Piped namespace var to locust master KNS name
- Bumped transformers version for Gemma support
=> Adding Jetstream support to locust solution.

cloudbuild.yaml
Error: https://github.com/GoogleCloudPlatform/ai-on-gke/pull/524#issuecomment-2067479350
=> Fix cloudbuild error

applications/rag/frontend/main.tf
Frontend sometimes gets OOM-killed. Set guaranteed QOS.
=> Bump rag frontend resource requests

cloudbuild.yaml
Fix output of when rag prompt fails.
=> quick fix or rag prompt test output

tutorials-and-examples/tpu-examples/training/gpt/Dockerfile
Swapping the checkout and install to make sure we install the checkout and not the latest transformers
=> Update Dockerfile transformer install order

gke-batch-refarch
Adding symlink to the new location for gke-batch-refarch.
=> Symlink for gke-batch-refarch

applications/ray/README.md, applications/ray/variables.tf, applications/ray/workloads.tfvars
Also add instructions to use a standard cluster if preferred.
=> Set the default GKE cluster type for ray to GKE Autopilot.

applications/jupyter/README.md, applications/jupyter/variables.tf, applications/jupyter/workloads.tfvars, applications/ray/README.md, applications/ray/variables.tf, applications/ray/workloads.tfvars, infrastructure/README.md
Cherry-pick #599 and #618 to the release-1.1 branch.
=> Cherry-pick #599 and #618 to release-1.1

applications/rag/README.md, applications/rag/metadata.yaml, applications/rag/variables.tf, applications/rag/workloads.tfvars
Remove DNS troubleshooting information, as this has been patched.
=> Update RAG to use Autopilot by default

modules/jupyter/tests/test_hub.py
Cherry-pick #643 to release-1.1 branch
=> Cherry-pick #643 to release-1.1 branch

tutorials-and-examples/inference-servers/checkpoints/Dockerfile, tutorials-and-examples/inference-servers/checkpoints/README.md, tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh, tutorials-and-examples/inference-servers/jetstream/http-server/Dockerfile, tutorials-and-examples/inference-servers/jetstream/http-server/http_server.py, tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server/Dockerfile, tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server/jetstream_pytorch_server_entrypoint.sh, tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/README.md, tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/checkpoint-job.yaml, tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/deployment.yaml, tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/pd-deployment.yaml, tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/storage.yaml
Jetstream Pytorch on GKE single host user guide
- additionally revise checkpoint converter to include jetstream-pytorch conversion
- update http server source location
=> Add soruce files for Jestream Pytorch on GKE single host user guide

cloudbuild.yaml, tpu-provisioner/cloudbuild.yaml
=> TPU provisioner cloudbuild step

cloudbuild.yaml
Parallel the application builds. Run Jupyter/Rag/Ray at the same time in difference namespaces.
=> Parallel all the applications within cloudbuild test

tpu-provisioner/internal/cloud/gke.go, tpu-provisioner/internal/cloud/gke_test.go
Add support for location hint label
=> [TPU Provisioner] Add support for location hint label

applications/jupyter/README.md
=> Remove information about nip.io

tpu-provisioner/README.md
Update usage instructions for TPU provisioner in the README
=> [TPU Provisioner] Update usage instructions for TPU provisioner

tpu-provisioner/internal/cloud/gke.go
Log JobSet name that triggered node pool creation
=> [TPU Provisioner] Log JobSet name that triggered node pool creation

tpu-provisioner/admission_controller/test/admission_controller_test.py
=> [TPU Provisioner Admission Controller] Update comment

best-practices/ml-platform/README.md
Link to the notebook packaging guide
=> Add notebook packaging link

tutorials-and-examples/gpu-examples/training-single-gpu/src/tensorflow-mnist-example/tensorflow_mnist_train_distributed.py, tutorials-and-examples/tpu-examples/training/gpt/Dockerfile
=> fix training on gke tutorial

tpu-provisioner/admission_controller/README.md, tpu-provisioner/admission_controller/manifests/manifest.yaml, tpu-provisioner/admission_controller/test/e2e/manifests/test-disabled-provisioning.yaml, tpu-provisioner/admission_controller/test/e2e/manifests/test-location-hint-no-reservation.yaml, tpu-provisioner/admission_controller/test/e2e/manifests/test-location-hint-with-reservation.yaml, tpu-provisioner/admission_controller/test/e2e/manifests/test-nonjobset-job.yaml, tpu-provisioner/admission_controller/test/e2e/test.sh
* Avoid mutation when provisioning is disabled
* Avoid mutation for Jobs not managed by a JobSet
* Add e2e test script and cases
=> [TPU Provisioner] Add admission label selectors and e2e test script

benchmarks/README.md, benchmarks/benchmark/tools/locust-load-inference/sample-dashboards/tgi-dashboard.yaml, benchmarks/benchmark/tools/locust-load-inference/sample-tfvars/tgi-sample.tfvars, benchmarks/inference-server/text-generation-inference/sample-terraform.tfvars, benchmarks/infra/stage-1/sample-tfvars/gpu-sample.tfvars, benchmarks/infra/stage-2/sample-tfvars/gpu-sample.tfvars, benchmarks/infra/stage-2/variables.tf
Update readme and default vars for cleaning up quickstart README.md top level
=> clean up TGI quickstart pathway

benchmarks/README.md
Add some additional info to the current main benchmarks README.md quickstart guide
=> update main README.md quickstart guide

modules/jetstream-maxtext-deployment/templates/prometheus-adapter/hpa.jetstream.yaml.tftpl, modules/jetstream-maxtext-deployment/templates/prometheus-adapter/values.yaml.tftpl, modules/prometheus-adapter/main.tf
Various nits in Maxtext related terraform modules, other changes to align deployments between ai-on-gke and public docs
=> Terraform modules cleanup

applications/rag/frontend/container/Dockerfile, applications/rag/frontend/container/requirements.txt, applications/rag/frontend/main.tf
fix vulnerability issue CVE-2024-6387
=> Update RAG fronend docker image

modules/jetstream-maxtext-deployment/README.md, modules/jetstream-maxtext-deployment/main.tf, modules/jetstream-maxtext-deployment/templates/deployment.yaml.tftpl, modules/jetstream-maxtext-deployment/templates/podmonitoring-tpu.yaml.tftpl, modules/jetstream-maxtext-deployment/variables.tf, tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/README.md, tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/terraform/sample-terraform.tfvars, tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/terraform/variables.tf
Added PodMonitoring to scrape TPU metrics with higher frequency (15s)
=> TPU Metrics PodMonitoring

tools/gke-disk-image-builder/script/startup.sh
Reduce hitting docker hub rate limits by trying mirror.gcr.io first.
=> add mirror.gcr.io registry mirror

contributing.md
Update contributing.md to include description of how to find build logs
=> Update contributing.md to include description of how to find build logs

scripts/network-setup/v6e-network-optimization.yaml
This checks in a new DaemonSet composed primarily of an initContainer running a network optimization bash script.
The script itself does a number of things that Google has measured to improve network performance. This includes "IRQ spreading", which ensures that each vnic is having interrupts processed on a distinct set of cores, various TCP settings, and enabling larger gve driver packet buffers, which improve performance when a large MTU is used.
=> Adding a v6e network optimization daemonset to ai-on-gke repository.

best-practices/ml-platform/examples/use-case/fine-tuning/pytorch/src/fine_tune.py
Fix for below issues:
ML Flow Issue1: Multiple versions of single experiment created in ml flow (race condition among the processes)
ML Flow Issue2: Multiple model registration for single experiment
ML Flow Issue3: System metrics not reported in Multi Node scenarios
=> Kr finetune mlflow

best-practices/ml-platform/examples/use-case/data-preparation/gemma-it/manifests/job.yaml, best-practices/ml-platform/examples/use-case/data-processing/ray/manifests/job.yaml, best-practices/ml-platform/examples/use-case/fine-tuning/pytorch/manifests/fine-tune-a100-dws.yaml, best-practices/ml-platform/examples/use-case/fine-tuning/pytorch/manifests/fine-tune-h100-dws.yaml, best-practices/ml-platform/examples/use-case/fine-tuning/pytorch/manifests/fine-tune-l4-dws.yaml, best-practices/ml-platform/examples/use-case/model-eval/manifests/deployment-a100.yaml, best-practices/ml-platform/examples/use-case/model-eval/manifests/deployment-l4.yaml, best-practices/ml-platform/examples/use-case/model-eval/manifests/job.yaml
add labels to each of the example use cases pod specs
=> add ml-platform use case labels

tutorials-and-examples/kserve/README.md
Add tutorial to install KServe on GKE Autopilot.
=> fix: add tutorial for kserve on gke

benchmarks/infra/stage-1/modules/gke-infra/main.tf
fixes #834 
Successfully ran stage-1 with this version appended to the module
=> fix mismatch in tf version dependencies

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
We currently cannot run experements where the number of prompts exceeds the size of the dataset (for us ~30k prompts), this change makes it so we now instead just filter the dataset and then select randomly from it.
=> Make Prompts Reusable for Very Large Experements

tutorials-and-examples/skypilot/README.md, tutorials-and-examples/skypilot/train.yaml
Move to use us-west1-a which has more L4.
=> fix: update skypilot tutorial

tutorials-and-examples/skypilot/README.md
=> fix: improve SkyPilot tutorial

tools/gke-disk-image-builder/README.md
`ctr image pull` only works with image with tag and will fail for images with tags.
=> Clarify container-image should have a tag in disk image building

tutorials-and-examples/skypilot/dws-and-kueue/README.md
Just a note to use nightly version until fix for https://github.com/skypilot-org/skypilot/issues/4542 gets released when running on autopilot. 
Also adds troubleshooting step if encountered
=> add note to use nightly when using serve on autopilot

tutorials-and-examples/skypilot/dws-and-kueue/variables.tf
Just fixes extra comment characters
=> fix header on variables file

CODEOWNERS
Update CODEOWNERS for tpu-provisioner maintainers
=> Update CODEOWNERS for tpu-provisioner

tutorials-and-examples/nvidia-bionemo/esm2/README.md
- support for L4
- typos and format fix
=> feat: bionemo training l4 support added

tpu-provisioner/internal/cloud/gke.go, tpu-provisioner/internal/cloud/gke_test.go
- For single node topologies, placement policy is not needed and tpuTopology being present will be rejected by the control plane
- Fix rounding issue with 1x1 topology returning 0 nodes
=> Fixes 2 related issues when using small topologies

ray-on-gke/examples/notebooks/raytrain-stablediffusion.ipynb
Small fix for notebook not able to display on GitHub.
=> Fix notebook display issue

tutorials-and-examples/tpu-examples/training/mnist-single-tpu/README.md
=> Fix a broken link in the README

tutorials-and-examples/skypilot/dws-and-kueue/README.md
With the latest SkyPilot release Autopilot no longer has issue with the 0 gpu selectors. 
https://github.com/skypilot-org/skypilot/releases/tag/v0.8.0
=> Remove skypilot nightly

applications/rag/frontend/container/Dockerfile, applications/rag/frontend/container/requirements.txt
bump Python version to fix vulnerabilities
=> bump Python version to fix vulnerabilities

applications/hcc/README_update_zone.md
- Add readme for scripts to update regions and zones
- todo: automate the scripts
=> Add readme for scripts to update regions and zones

infrastructure/main.tf
=> Update cloud NAT region as per GKE region.

infrastructure/outputs.tf, tutorials-and-examples/llamaindex/rag/README.md, tutorials-and-examples/llamaindex/rag/app/Dockerfile, tutorials-and-examples/llamaindex/rag/app/cmd/ingest_data.py, tutorials-and-examples/llamaindex/rag/app/rag_demo/__init__.py, tutorials-and-examples/llamaindex/rag/app/rag_demo/main.py, tutorials-and-examples/llamaindex/rag/app/requirements.txt, tutorials-and-examples/llamaindex/rag/cloudbuild.yaml, tutorials-and-examples/llamaindex/rag/redis-stack.yaml, tutorials-and-examples/llamaindex/rag/templates/ingest-data-job.yaml, tutorials-and-examples/llamaindex/rag/templates/ollama-deployment.yaml, tutorials-and-examples/llamaindex/rag/templates/rag-deployment.yaml, tutorials-and-examples/llamaindex/rag/terraform/backend.tf, tutorials-and-examples/llamaindex/rag/terraform/default_env.tfvars, tutorials-and-examples/llamaindex/rag/terraform/main.tf, tutorials-and-examples/llamaindex/rag/terraform/outputs.tf, tutorials-and-examples/llamaindex/rag/terraform/variables.tf
This PR adds a guide for Llamaindex RAG running on GKE
=> Llamaindex RAG guide

applications/hcc/a3mega_workloads.tfvars, applications/hcc/a3ultra_workloads.tfvars, applications/hcc/main.tf, applications/hcc/modules/nemo/variables.tf, applications/hcc/node_count.tf, applications/hcc/variables.tf
- not null validation
- node count validation
=> add basic validations to hcc

applications/hcc/main.tf, applications/hcc/variables.tf
- grant bucket object user permission to default sa
- enable resource manager api for project
=> fix permission bug for bucket access

applications/hcc/metadata.display.yaml
Update supported machine type zone list
=> Update region/zone list

cloudbuild.yaml
add random cluster name in cloudbuild file
=> fix cicd pipeline

applications/hcc/README_update_zone.md, applications/hcc/cloudbuild_update_zone_region.yaml
1. update readme for updating regions and zone for a3m and a3u
2. add cloudbuild yaml file to enable the automation for scripts
=> Automatically update regions and zones

cloudbuild.yaml
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
/kind cleanup
> /kind documentation
> /kind enhancement
**What this PR does / Why we need it**:
We've already removed the Jupyter QSS application code in https://github.com/GoogleCloudPlatform/ai-on-gke/pull/1069/files. This PR removes it from the E2E test accordingly.
**Which issue(s) this PR fixes**:
CI failures like https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/ae8dffdb-fe62-4e11-ba44-949dcd7fb0d2;step=2?e=13802955&hl=en&invt=Abu1Zw&mods=logs_tg_staging&project=gke-ai-eco-dev
**Special notes for your reviewer**:
=> Remove jupyter QSS e2e test

tutorials-and-examples/nvidia-bionemo/fine-tuning/README.md, tutorials-and-examples/nvidia-bionemo/pretraining/README.md
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
documentation
**What this PR does / Why we need it**:
Fixes issue: https://github.com/GoogleCloudPlatform/ai-on-gke/issues/1088 to take care of readme updates for pretraining and finetuning.
**Which issue(s) this PR fixes**:
Closes #1088
**Special notes for your reviewer**:
Verified working with new updates
=> fix: NV bionemo pretraining and finetuning doc updates

tutorials-and-examples/inference-servers/jetstream/README.md
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
/kind cleanup
> /kind documentation
> /kind enhancement
**What this PR does / Why we need it**:
Adding warning to deprecate code as a new official guide was launched
=> Add warning about new code

applications/hcc/metadata.display.yaml
=> update a3u region

benchmarks/65k-cpu-nodes-simulated-ai-benchmark.md, benchmarks/README.md, benchmarks/accelerator-based-ai-benchmark.md, benchmarks/benchmark/README.md, benchmarks/benchmark/dataset/README.md, benchmarks/benchmark/dataset/ShareGPT_v3_unflitered_cleaned_split/README.md, benchmarks/benchmark/tools/README.md, benchmarks/benchmark/tools/dlio/README.md, benchmarks/benchmark/tools/locust-load-inference/README.md, benchmarks/benchmark/tools/model-load-benchmark/README.md, benchmarks/benchmark/tools/profile-generator/README.md, benchmarks/inference-server/README.md, benchmarks/inference-server/jetstream/README.md, benchmarks/inference-server/text-generation-inference/README.md, benchmarks/inference-server/triton/README.md, benchmarks/inference-server/vllm/README.md, benchmarks/infra/accelerator-cluster/README.md, benchmarks/infra/accelerator-cluster/stage-1/README.md, benchmarks/infra/accelerator-cluster/stage-2/README.md, benchmarks/orchestration/README.md
What type of PR is this?
/kind cleanup
What this PR does / Why we need it:
Deprecating old content after talking with owners. All these guides are no longer maintained and will not be transferred to the new benchmarking repository.
=> Deprecations
