GoogleCloudPlatform/ai-on-gke

jobset/pytorch/README.md

This is a simple step-by-step guide for using the JobSet API to run a distributed ML training workload with PyTorch.
cc @ahg-g

Add example using the JobSet API to run a distributed ML training workload with PyTorch

---

ray-on-gke/README.md
ray-on-gke/platform/modules/gke_standard/main.tf

- small fix in `read.md`, command for port-forwarding needs namespace user defined instead of `ray`.
- remove default node pool creation in terraform template. We are not using the default node pool and it's not manageable.

update read.md and remove default node pool in tf

---

ray-on-gke/platform/modules/gke_standard/output.tf

The cluster CA certificate is public and not a sensitive resource. Fix a typo.

Remove sensitive from cluster_certificate in output.tf

---

ray-on-gke/platform/modules/gke_standard/main.tf
ray-on-gke/user/modules/kuberay/kuberay-values.yaml

**What is this PR for:**
A100s gpus/A2 machines are facing stockout so this changes the default machine type and gpu type for the cluster and ray.

update default machine type and gpu type

---

ray-on-gke/platform/modules/gke_standard/main.tf

**What this PR is for:**
This change adds the correct labels to the node so that it matches the nodeSelector labels in the ray config yaml. Currently, without it, the ray cluster will run into an error with `Pod's node affinity/selector`

Add labels to match ray nodeselector

---

ray-on-gke/user/jupyterhub/jupyter_config/config.yaml

This should fixes the issue of 
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):│ jupyterhub:│ - singleuser.cpu.limit: Invalid type. Expected: [number,null], given: string│ - singleuser.cpu.guarantee: Invalid type. Expected: [number,null], given: string
```
When running jupyterhub, with current config, it runs into the error above. This fixes the issue.

fix values for jupyterhub cpu and mem

---

ray-on-gke/README.md

Currently the Jupyter settings/passord link is broken because of the Juptyer refactor PR. This PR updates the link.

Updated Jupyter settings link to notebook passwords

---

ray-on-gke/README.md
ray-on-gke/user/jupyterhub/jupyter_config/config.yaml

Added default images to jupyterhub and added a note in the readme that lets the user know that the file can be changed. But we can also have different default image as well, since there isn't a point to have 3 profiles with the same image.

Add image to jupyter config and more to readme

---

ray-on-gke/platform/modules/gke_standard/main.tf
ray-on-gke/platform/modules/gke_standard/variables.tf
ray-on-gke/user/jupyterhub/jupyterhub.tf
ray-on-gke/user/jupyterhub/variables.tf

TPU V4 is only available in us-central2-b. Otherwise everytime we need to manually add this in template so can pass through. 
And a bit auto formatting.

add tpu node location in template

---

ray-on-gke/README.md

Command in `ray-on-gke/README.md` was missing a closing backtick. Also, italicize the _Note:_ portion.

Fix missing backtick in README

---

gke-tpu-examples/single-host-inference/jax/bert/install-bert.yaml
gke-tpu-examples/single-host-inference/jax/stable-diffusion/install-stable-diffusion.yaml
gke-tpu-examples/single-host-inference/tf/resnet50/model-conversion.yml

- download the demo source code from github repo instead of from gcs bucket

Replace gcs bucket with github repo in TPU demo

---

jobset/pytorch/README.md

Fixes #46 
We reorganized the JobSet examples directory structure and so now we need to update the corresponding URL here as well.

Uupdate jobset example yaml

---

gke-platform/main.tf
gke-platform/modules/gke_autopilot/main.tf
gke-platform/modules/kuberay/kuberay-operator-autopilot-values.yaml
gke-platform/modules/kuberay/kuberay-operator-values.yaml
gke-platform/modules/kuberay/kuberay.tf
gke-platform/modules/kuberay/variables.tf
ray-on-gke/user/main.tf
ray-on-gke/user/modules/kuberay/kuberay-autopilot-values.yaml
ray-on-gke/user/modules/kuberay/kuberay.tf
ray-on-gke/user/modules/kuberay/variables.tf
ray-on-gke/user/variables.tf

Making a few changes to support Ray on Autopilot:
* If `enable_autopilot` is set, bypass the init containers for Ray workers
* Use a custom Kuberay cluster spec if the cluster is Autopilot. The Kuberay cluster contains 3 worker groups - small (only CPU), medium (1 GPU), and large (8 GPUs).

Ray on Autopilot 

---

tutorials/finetuning-llama-7b-on-l4/README.md
tutorials/serving-llama2-70b-on-l4-gpus/README.md

There should be an empty line before embedmd otherwise it will render as normal text. This fixes that by adding the empty lines.
Also reorder the steps in llama 70b to execute deployment creation after creating the YAML file which flows better.

tutorials: fix embedmd and reorder llama 70b steps

---

training-single-gpu/src/gke-config/standard-tensorflow-bash.yaml
training-single-gpu/src/gke-config/standard-tf-mnist-batch-predict.yaml
training-single-gpu/src/gke-config/standard-tf-mnist-train.yaml

- Remove unnecessary pv/pvc logic from the training-single-gpu examples as the yaml files use the CSI ephemeral inline volumes.
- Remove unnecessary uid and gid mount options.
- Explicitly declare resource limits in the train and predict jobs to make them work on Autopilot clusters.

remove unnecessary pv/pvc logic from training-single-gpu examples

---

ray-on-gke/cloudbuild.yaml

[EZ] remove text color info in cloudbuild logs 

---

jupyter-on-gke/README.md
jupyter-on-gke/authentication/README.MD
jupyter-on-gke/variables.tf

This will enable the authentication by default. It also includes a step to create the image that is needed for auth.

Enable auth and link instructions for creating image needed for auth

---

jupyter-on-gke/README.md
jupyter-on-gke/allowlist
jupyter-on-gke/jupyterhub.tf
jupyter-on-gke/variables.tf

Add all the users/groups specified in the `allowlist` file as web app users for IAP.

Automatically add principals as web users from allowlist file

---

gke-platform/modules/kuberay/kuberay.tf

This ensures we continue to run the current helm chart version for kuberay-operator (0.6.1)  even after v1.0.0 is released.

pin helm chart version for kuberay-operator to 0.6.1

---

gke-platform/modules/kuberay/kuberay.tf
gke-platform/modules/kuberay/variables.tf
ray-on-gke/user/modules/kuberay/variables.tf

I got the impression from existing variables in the kuberay module that we intended to install kuberay-operator in the `ray` namespace, but since the namespace definition was missing from `helm_release` we are still installing kuberay-operator in the `default` namespace. This PR adds the namespace field to the helm release of kuberay-operator and changes the default value for the namespace to `ray-system`.

install kuberay-operator in a dedicated namespace (ray-system)

---

ray-on-gke/user/modules/kuberay/kuberay.tf

In https://github.com/GoogleCloudPlatform/ai-on-gke/pull/81 and https://github.com/GoogleCloudPlatform/ai-on-gke/pull/96 we pinned the kuberay-operator image version and the helm chart version to v0.6.1. However, the ray-cluster chart which installs the default RayCluster is using the latest version (v1.0.0-rc.1) which is trying to use the new v1 version of the CRDs that are not supported in v0.6.1 yet.

pin ray-cluster helm chart version to 0.6.1

---

gke-platform/main.tf
gke-platform/modules/gke_standard/main.tf
gke-platform/modules/gke_standard/variables.tf
gke-platform/modules/kuberay/kuberay-operator-autopilot-values.yaml
gke-platform/modules/kuberay/kuberay-operator-values.yaml
gke-platform/modules/kuberay/kuberay.tf
gke-platform/variables.tf
ray-on-gke/.gitignore
ray-on-gke/rayservice-examples/README.md
ray-on-gke/rayservice-examples/gradio.yaml
ray-on-gke/rayservice-examples/ingress/README.md
ray-on-gke/rayservice-examples/ingress/gateway.yaml
ray-on-gke/rayservice-examples/ingress/healthcheckpolicy.yaml
ray-on-gke/rayservice-examples/ingress/httproute.yaml
ray-on-gke/rayservice-examples/model/meta-llama--Llama-2-13b-chat-hf.yaml
ray-on-gke/rayservice-examples/model/meta-llama--Llama-2-7b-chat-hf.yaml
ray-on-gke/rayservice-examples/model/tiiuae--falcon-7b.yaml
ray-on-gke/rayservice-examples/rayservice-meta-llama2-13b.yaml
ray-on-gke/rayservice-examples/rayservice-meta-llama2-70b-quantized.yaml
ray-on-gke/rayservice-examples/rayservice-meta-llama2-7b.yaml
ray-on-gke/rayservice-examples/rayservice-tiiuae-falcon-40b-quantized.yaml
ray-on-gke/rayservice-examples/rayservice-tiiuae-falcon-7b.yaml

- Modify `gke-platform` so that gpu-pool machinetype, accelerator and nodepool locations are variables. Primarily to support L4 accelerators
- Examples for llm serving with rayllm & ray serve (with various model parameter sizes)

Examples for Ray inferencing

---

gke-disk-image-builder/script/startup.sh

Fixes #124 
Evidently, the device node for hyperdisks is in not in the same location in the filesystem as other disk types (1st one /dev/sdb, 2nd one /dev/sdc, and so on). 
To fix this, we can use the device name explicitly: `/dev/disk/by-id/google-<device name>` (for non-partitioned disks) and `/dev/disk/by-id/google-<device name>-part1` (for partitioned disks).
The changes in this PR use the device name explicitly, as defined [here](https://github.com/GoogleCloudPlatform/ai-on-gke/blob/71ebab897948cbca722c9abf4ec3ff2bc1318b3b/gke-disk-image-builder/imager.go#L111).
I tested these changes manually with the following command and it worked:
`go run ./cli --project-name=$PROJECT_NAME --image-name=triton-2309-py3-hd --zone=$ZONE --gcs-path=gs://$GCS_PATH/ …

[gke-disk-image-builder] Set device name explicitly in startup.sh

---

gke-platform/main.tf
gke-platform/modules/gke_autopilot/main.tf
gke-platform/modules/gke_autopilot/variables.tf
gke-platform/modules/gke_standard/main.tf
gke-platform/modules/gke_standard/variables.tf
gke-platform/variables.tf

Add default cluster labels so users can easily find clusters created using terraform modules in this repo

gke-platform: add default cluster labels to GKE clusters

---

jupyter-on-gke/jupyter_config/config-selfauth.yaml

We now have a public AR repo that hosts our authentication class image. This PR changes the default image used.

Change image used by Jupyterhub

---

jupyter-on-gke/jupyterhub.tf

When you turn off auth, it will still try to create oauth client for you if you leave the variable blank. This adds the add_auth to the check.

Fixes bug with client creation when auth is turned off

---

gke-disk-image-builder/README.md
gke-disk-image-builder/cli/main.go
gke-disk-image-builder/imager.go

Some users need the VM instance used to build the disk image to exist in a custom VPC network and/or subnet, rather than the default ones.
This change parameterizes the network and subnet fields of the GCE instance creation call and adds two new optional flags the user can specify: `--network` and `--subnet`.

[GKE Disk Image Builder] Parameterize network and subnet

---

jupyter-on-gke/authentication/authenticator/gcpiapjwtauthenticator/gcpiapjwtauthenticator.py

when logged in, it should show: ![image](https://github.com/GoogleCloudPlatform/ai-on-gke/assets/17622084/824b6b9e-c20b-464f-acae-d5939e9048e4)
and when the notebook starts, it should look like this in the terminal: ![image](https://github.com/GoogleCloudPlatform/ai-on-gke/assets/17622084/830a3565-861a-4ebf-a2bc-0558ea37af8a)

Modified username used by jupyterhub

---

gke-disk-image-builder/README.md
gke-disk-image-builder/cli/main.go
gke-disk-image-builder/imager.go
gke-disk-image-builder/script/startup.sh

The job names are used to provision intermediate resources (VMs, disks). When workflows are run concurrently, there would be name collisions. This change allows users to run more than 1 workflow at a time.
b/315384952
TESTED: manually

Allow customizing job name.

---

gke-disk-image-builder/script/startup.sh

Add -p to cp command to preserve mode, ownership, and timestamps, otherwise the new snapshot directories will use root as owners and groups.

Add -p to cp command to preserve mode, ownership, and timestamps

---

gke-disk-image-builder/README.md
gke-disk-image-builder/cli/main.go
gke-disk-image-builder/imager.go

b/315387164
TESTED: manually run with --image-family-name flag.

Support customizing image family name.

---

jupyter-on-gke/README.md
jupyter-on-gke/jupyter_config/config-selfauth.yaml
jupyter-on-gke/profiles.md

Adds a profile that selects the TPU node.

Adding TPU option to Jupyterhub

---

gke-batch-refarch/02_platform/monitoring/install-prometheus.sh
gke-batch-refarch/cloudbuild-create.yaml

Fixes #191.
Propagated environment variables from the Cloud Build yaml into the installation script. Added timeout to the wait for monitoring CRD creation.

Made the installation flow for Kueue Grafana dashboard smoother

---

gke-disk-image-builder/README.md
gke-disk-image-builder/cli/main.go
gke-disk-image-builder/imager.go

Fixes #166 
Made sure it still works with no `--service-account` flag as well:
```bash
go run ./cli \
--project-name=$PROJECT_NAME --machine-type=n2-standard-4 \
--image-name=$IMAGE_NAME \
--zone=$ZONE \
--gcs-path=gs://$GCS_PATH/ \
--disk-size-gb=$DISK_SIZE_GB \
--container-image=docker.io/library/python:3.8
[secondary-disk-image]: 2024-02-16T15:22:27-05:00 Step "create-image" (CreateImages) successfully finished.
[secondary-disk-image]: 2024-02-16T15:22:27-05:00 Workflow "secondary-disk-image" cleaning up (this may take up to 2 minutes).
[secondary-disk-image]: 2024-02-16T15:23:17-05:00 Workflow "secondary-disk-image" finished cleanup.
Image has successfully been created at: projects/REDACTED/global/images/test-img-build
```

Add --service-account flag to gke-disk-image-builder cli

---

gke-disk-image-builder/script/startup.sh

Tested by creating a secondary boot disk node pool and verifying images.metadata is there:
```
gke-riptide-cluster-np2-64966d83-9dlk /home/ruiwen # cat /mnt/disks/gke-secondary-disks/gke-nginx-latest-test-disk/images.metadata
REF                                                                     TYPE                                    DIGEST                                                                  SIZE     PLATFORMS                                                                                                               LABELS
docker.io/library/nginx:latest                                          application/vnd.oci.image.index.v1+json sha256:ea97e6aace270d82c73da382ea1a8c42d44b9dc11b55159104e21c49c687e7fb 67.3 MiB linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v …
```

Write image info when generating secondary boot disk image

---

applications/ray/raytrain-examples/raytrain-with-gcsfusecsi/kuberaytf/user/modules/kuberay/kuberay-values.yaml
modules/kuberay-cluster/kuberay-autopilot-values.yaml
modules/kuberay-cluster/kuberay-tpu-values.yaml
modules/kuberay-cluster/kuberay-values.yaml

In https://github.com/GoogleCloudPlatform/ai-on-gke/pull/182 we introduced a `created-by: ray-on-gke` label. When the `applications/ray/` folder was introduced, these labels were removed. 
This PR adds them back to the new `applications/ray` modules

re-add created-by: ray-on-gke label for ray modules

---

gke-disk-image-builder/cli/main.go
gke-disk-image-builder/imager.go
gke-disk-image-builder/script/startup.sh
gke-disk-image-builder/script/verify.sh

This change adds two flags:
1. `--store-snapshot-checksum`, default true. When true, the image building process will calculate and store the md5sum for all snapshots, and store the md5sums in snapshots.metadata.
2. `--verify-only`, default false. When true, the cli will NOT build anything, but only read the disk image passed through `image-name` flag, calculate the md5sums for all snapshots, and compare them with the ones stored in  snapshots.metadata. If no md5sums are available in the file, it will return an error. If the comparison fails on any snapshot, it will output:
```
Feb 14 23:10:22 debian google_metadata_script_runner[1189]: startup-script-url: sha256:4a7b85ea735027381ceeb667ca753c469333c019a4ae8aa1bbd03584ba116dde snapshots/6/fs 2465c5e374a0c0b520921c169c6bee41
Feb 14 23:10:22 …
```

Add functionality to validate disk image

---

applications/jupyter/main.tf
applications/rag/main.tf
applications/ray/main.tf
modules/jupyter/main.tf

Originally introduced in https://github.com/GoogleCloudPlatform/ai-on-gke/pull/228
This blocks local development, as all modules are now pulled from Github.

Revert modules to use relative paths

---

applications/rag/frontend/versions.tf
applications/rag/main.tf
applications/rag/metadata.display.yaml
applications/rag/metadata.yaml
applications/rag/variables.tf
applications/rag/workloads.tfvars
infrastructure/outputs.tf
modules/cloudsql/versions.tf
tutorials/hf-tgi/versions.tf

- Create a cluster with appropriate nodepools/other config on behalf of the user
- Still allow bringing your own cluster
- Update marketplace blueprints with cluster creation options

Add support to RAG application to create a cluster for the user, or allow them to bring their own cluster

---

applications/ray/kuberay-tpu-webhook/Makefile
applications/ray/kuberay-tpu-webhook/deployments/deployment.yaml

This PR changes the image tags to `v1.0` rather than `latest` for webhook for the branch release cut. Manually tested to ensure webhook could deploy correctly and successfully pull the image.

Update Ray TPU Webhook Image Tags to v1.0

---

applications/rag/frontend/main.tf
applications/rag/frontend/variables.tf
applications/rag/main.tf
applications/rag/variables.tf
applications/ray/raytrain-examples/raytrain-with-gcsfusecsi/kuberaytf/user/modules/service_accounts/versions.tf
applications/ray/versions.tf
modules/cloudsql/main.tf
modules/cloudsql/variables.tf

Modified variables & related code to accept cloudsql instance name as a variable. 
This doesn't change user experience (Readme / Notebooks) however enables cloudbuild to set unique instance names.

Configure CloudSQL instance name

---

applications/jupyter/main.tf
applications/rag/frontend/main.tf
applications/rag/frontend/variables.tf
applications/rag/frontend/versions.tf
applications/rag/main.tf
applications/rag/variables.tf
applications/rag/workloads.tfvars
modules/jupyter/main.tf
modules/kuberay-monitoring/main.tf
modules/kuberay-monitoring/outputs.tf
modules/kubernetes-namespace/main.tf
tutorials/hf-tgi/outputs.tf

- introduce namespace helm module to prepare namespace before actual module, earlier this was done using depends_on = kuberay_operator
- optmise frontend module to read endpoint from module output and remove addtional data sources.
- set l4 node-locations default to us-central1-a for less quota or stockout issues.
- disable IAP as default option. 
- tf plan reduced to 40s to 8s

Update dependents and fix frontend issues

---

applications/rag/main.tf

- 'kuberay_monitoring' module should depend on 'namespace' module, otherwise the gmp_engine does not come up reliably

Fix kuberay_monitoring module dependency for RAG

---

.github/workflows/ci.yaml
applications/jupyter/workloads-without-iap.example.tfvars
applications/rag/main.tf
applications/rag/variables.tf
applications/rag/workloads.tfvars
applications/ray/raytrain-examples/raytrain-with-gcsfusecsi/kuberaytf/user/modules/service_accounts/versions.tf
applications/ray/versions.tf
benchmarks/benchmark/tools/locust-load-inference/sample-terraform.tfvars
infrastructure/tfvars_tests/standard-gke-public.platform.tfvars
modules/iap/iap.tf
modules/iap/variables.tf
modules/kuberay-monitoring/main.tf
tutorials/hf-tgi/outputs.tf

- Add github actions for TF fmt, TF validate and TF init

Add github actions for tf lint check

---

applications/ray/kuberay-tpu-webhook/Makefile

So contributors don't have to build the Go binary locally in order to build the docker image.

kuberay-tpu-webhook: remove webhook as pre-requisite target of docker-build

---

applications/rag/README.md
applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb
modules/kuberay-cluster/kuberay-autopilot-values.yaml

- Ray version 2.7.1 appears to fix some Ray Autoscaler bugs
- Lower resource allocation to better utilize node capacity (recommended 1:1 matching between k8s and Ray nodes):
- Head: `c3-standard-4`
- CPU worker:`c3-standard-8`
- GPU worker:`g2-standard-8`
- Pretty print Ray job info in Jupyter notebook
- Fix README wording

Upgrade Ray version for Autopilot; shrink worker resource allocation

---

applications/rag/frontend/main.tf
cloudbuild.yaml
modules/jupyter/main.tf
modules/kuberay-operator/kuberay.tf

- Upgrade machineType for Cloudbuild Instance
- Pin workload ID TF module version

Optimize CI

---

applications/rag/main.tf
applications/rag/metadata.display.yaml
applications/rag/metadata.yaml
applications/rag/variables.tf
cloudbuild.yaml
infrastructure/main.tf
infrastructure/outputs.tf
infrastructure/platform.tfvars
infrastructure/tfvars_examples/autopilot-gke-with-existing-network.platform.tfvars
infrastructure/tfvars_examples/autopilot-gke-with-new-network.platform.tfvars
infrastructure/tfvars_examples/platform.complete.tfvars
infrastructure/tfvars_examples/standard-gke-with-exisiting-network.platform.tfvars
infrastructure/tfvars_examples/standard-gke-with-new-network.platform.tfvars
infrastructure/tfvars_tests/standard-gke-public.platform.tfvars
infrastructure/variables.tf
modules/jupyter/main.tf

- support cluster_location parameter that accept region and zone to create gke cluster
- use T4 & L4 zones for gpu pools based on selected zones.

Add support for zonal gke standard cluster

---

applications/rag/frontend/container/main.py
applications/rag/frontend/container/rai/nlp_filter.py
applications/rag/frontend/container/static/script.js
applications/rag/frontend/container/templates/index.html

Fix the webpage hide un correctly and backend service type wrong
Tested-by: zlq on sandbox

Fix the nlp bug

---

tpu-provisioner/internal/controller/deletion_controller.go

This is needed to allow for more time for Jobs (and pods) to be recreated upon JobSet restart, since JobSet now uses foreground deletion to avoid [other issues](https://github.com/kubernetes-sigs/jobset/issues/392), so Job recreation is blocked until all of the pods from the previous Job are completely deleted. This means it may take longer than 4 seconds for the pods to begin rescheduling during failure recovery, so we should bump the interval to 60 seconds.

[TPU Provisioner] Bump node pool deletion check interval

---

modules/kuberay-operator/kuberay.tf

This token mounting is required for Ray Autoscaler.
Introduced in https://github.com/GoogleCloudPlatform/ai-on-gke/pull/303

Fix regression for kuberay-operator token mounting

---

benchmarks/inference-server/text-generation-inference/main.tf
benchmarks/inference-server/text-generation-inference/manifest-templates/text-generation-inference.tftpl
benchmarks/inference-server/text-generation-inference/variables.tf

Validated via tf deployment:
kubectl logs -n benchmark tgi-66f66b7b6f-np2nw
output shows max_concurrent_requests: 1000 in tgi server config

add max-concurrent-requests as option in TGI server

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py

Locust user task uses requests library as underlying infra.
To ensure Locust loadbalances across new TGI pods with autoscaling, close the connection for each request so a new one is opened.

locust close connections for each request

---

modules/jupyter/main.tf

- jupyter with IAP service account attribute was missing, leading to apply error.

fFx jupyter sa bug

---

benchmarks/benchmark/tools/dlio/README.md
benchmarks/benchmark/tools/dlio/main.tf
benchmarks/benchmark/tools/dlio/modules/dlio/job.tf
benchmarks/benchmark/tools/dlio/modules/dlio/podspec.tpl
benchmarks/benchmark/tools/dlio/modules/dlio/variables.tf
benchmarks/benchmark/tools/dlio/modules/parallelstore_storage/variables.tf
benchmarks/benchmark/tools/dlio/parser.py
benchmarks/benchmark/tools/dlio/variables.tf

this PR
- changes the DLIO job to automatically write back the results of DLIO runs to a second result bucket.
- added a python script to help walk the result folder tree and calculate average performance metrics across multiple pods' results.

write back dlio result to a separate result bucket and add parser script

---

applications/rag/README.md
applications/rag/example_notebooks/rag-kaggle-ray-sql-latest.ipynb
applications/rag/frontend/main.tf
applications/rag/frontend/variables.tf
applications/rag/main.tf
applications/rag/metadata.yaml
applications/rag/variables.tf
applications/rag/workloads.tfvars
infrastructure/main.tf
modules/kuberay-cluster/kuberay-autopilot-values.yaml
modules/kuberay-cluster/kuberay-gpu-values.yaml
modules/kuberay-cluster/kuberay-tpu-values.yaml
modules/kuberay-cluster/kuberay-values.yaml
modules/kuberay-cluster/main.tf
modules/kuberay-cluster/variables.tf

1) Pass already constructed cloud SQL instance connection name to Ray workers so users don't have to set it in the notebook
2) Set Cloud SQL region in frontend
3) Fix bug with cluster creation where random zones without GPU availability were being selected
4) Reduce SA name length (gets truncated when IM deployment prefix is added for Marketplace)

Improvements to Cloud SQL & cluster creation

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/run.sh
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py

Increase locust user task and connection timeout to handle long-running requests.
Currently defaults are:
user_task -> 5 min before master kills the user task
http requests connection timeout -> 60 seconds before connection timeout error (explains the 0 return from locust)
Setting extremely high default for now (3 hrs)
Will turn into tfvars variable if possible (only unknown in that is that http request connection_timeout is a user class variable, and have to confirm that it will respect arguments piped through to tasks.py file before it's instantiated.)

Increase locust user task and connection timeout

---

applications/rag/main.tf
applications/rag/variables.tf
applications/rag/workloads.tfvars

- Pass SQL instance name to module
- Use cluster_location as sql instance region, if not specified.

Fix SQL name and region

---

applications/rag/README.md
applications/rag/variables.tf
applications/rag/workloads.tfvars

GKE Rapid default version now supports Accelerator and Performance classes. Mark cluster creation optional in the README.
Plus miscellaneous README fixes

Implement rag terraform instructions for Autopilot

---

modules/jupyter/main.tf

5 minutes is barely cutting it and causing intermittent timeouts.

Double Jupyter deployment timeout

---

infrastructure/tfvars_examples/platform.complete.tfvars
infrastructure/variables.tf

Since a few months back we used the cluster label `created-by: ai-on-gke` by default. However, recently it was changed to `gke-profile: ai-on-gke`. This PR reverts the cluster label back to `created-by: ai-on-gke`.

revert default GKE cluster labels to created-by: ai-on-gke

---

applications/jupyter/main.tf
applications/jupyter/metadata.display.yaml
applications/jupyter/metadata.yaml
applications/jupyter/variables.tf
applications/rag/frontend/main.tf
applications/rag/frontend/variables.tf
applications/rag/main.tf
applications/rag/metadata.display.yaml
applications/rag/metadata.yaml
applications/rag/variables.tf
applications/ray/metadata.display.yaml
applications/ray/metadata.yaml
modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
modules/jupyter/jupyter_config/config-selfauth.yaml
modules/jupyter/main.tf
modules/jupyter/variables.tf
modules/kuberay-cluster/main.tf
modules/kuberay-cluster/values.yaml
modules/kuberay-cluster/variables.tf
tutorials-and-examples/hf-tgi/main.tf
tutorials-and-examples/hf-tgi/variables.tf

Adds a new variable `additional_labels` for rag, ray and jupyter.

support additional labels for rag, ray and jupyter

---

applications/ray/kuberay-tpu-webhook/main.go

This PR defaults the single-host Pod `TPU_WORKER_ID` to 0 to fix a bug that was incrementing the ID upon deletion and re-creation. This PR also updates the code to only inject `TPU_WORKER_HOSTNAMES` for multi-host podslices (previously an empty string would be injected). This PR was manually tested by creating both single-host and multi-host RayClusters using this template: https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.tpu-v4-singlehost.yaml and verifying that the env vars were set correctly even after multiple creations and deletions of the RayCluster.

Single-Host TPU Webhook Fix

---

applications/rag/main.tf
applications/rag/versions.tf
applications/ray/main.tf
applications/ray/versions.tf
modules/kuberay-monitoring/main.tf
modules/kuberay-monitoring/versions.tf

`kuberay-operator` appears to be deployed faster than the `gmp-operator`, causing `kuberay-monitoring` to create a `PodMonitorings` object before the GMP webhook server is ready to validate it.
Implement a delay between `kuberay-operator` startup and `kuberay-monitoring` deployment to ensure `gmp-operator` has time to start up. This delay can be adjusted based on perceived flakiness.
Fixes https://github.com/GoogleCloudPlatform/ai-on-gke/issues/402
Replaces https://github.com/GoogleCloudPlatform/ai-on-gke/pull/407
This lightweight solution is meant as a stop-gap, to be replaced with either of the two proper solutions:
1. Ensure gmp-operator is always running in the GKE CP.
2. Implement retry on the provider (https://github.com/hashicorp/terraform-provider-helm/issues/1058).

Wait for gmp-operator rollout before applying kuberay podmonitorings

---

modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
modules/jupyter/jupyter_config/config-selfauth.yaml

Jupyterhub image will use a tagged image instead of 'latest'. Tagged image should have less vulns.

have Jupyterhub use tagged image instead of 'latest'

---

applications/jupyter/metadata.yaml
applications/rag/main.tf
applications/rag/metadata.display.yaml
applications/rag/metadata.yaml
applications/rag/outputs.tf
applications/rag/variables.tf
applications/rag/workloads.tfvars
cloudbuild.yaml
infrastructure/platform.tfvars

- Auto-generate namespace for marketplace without user input, prefixed with the IM deployment name. This helps prevent issues with multiple RAG deployments landing on the same namespace.
- For RAG marketplace solution, always generate a new network with PSC enabled prefixed with the IM deployment_name

Improvements to Marketplace experience for RAG (auto generate network and namespace)

---

applications/ray/kuberay-tpu-webhook/Makefile
applications/ray/kuberay-tpu-webhook/certs/cert.yaml
applications/ray/kuberay-tpu-webhook/deployments/deployment.yaml
applications/ray/kuberay-tpu-webhook/main.go

This PR adds more `klog` logging statements to the webhook with more informative messages, viewable using `kubectl logs` when the webhook pod is running. This PR was tested by deploying a RayCluster with the webhook running, viewing the `kubectl logs` printed out, and verifying that all mutation operations occurred succesfully.

Add More Informative Logging Throughout Ray TPU Webhook

---

applications/ray/kuberay-tpu-webhook/main.go

This PR adds support for single-host, multi-slice TPU worker groups, which require the `TPU_NAME` and `TPU_WORKER_ID` env vars. Specifically, this PR changes the webhook to inject a `replicaIndex` label for all Ray worker pods requesting TPUs (previously injected a `multiHostReplica` label only for multi-host). Pods which are deleted and restart will be assigned the same `TPU_WORKER_ID`, `TPU_NAME`, and `replicaIndex`. This PR was manually tested by creating single-host, single-slice, multi-host, and multi-slice RayClusters and ensuring that all environment variables were injected correctly, even after multiple Pod deletions.

Ray Webhook Support for Single-Host, Multi-Slice TPUs

---

applications/rag/main.tf
applications/rag/variables.tf
applications/ray/main.tf
modules/iap/iap.tf
modules/kuberay-cluster/main.tf
modules/kuberay-monitoring/main.tf
modules/kuberay-monitoring/variables.tf

We are still seeing flakiness.
Pip installs are experiencing intermittent failures. Downgrading to 1.28 to rule out possibility of k8s or GKE regressions.
For the GMP operator, one explanation is that there are multiple system pods all starting up simultaneously and competing for resources, delaying `gmp-operator` startup. Bumping this to 60s to rule out this issue entirely. This shouldn't affect E2E creation, because the long tail is still CloudSQL instance creation.
Context: https://github.com/GoogleCloudPlatform/ai-on-gke/pull/418
Additionally, increase the Ray worker timeout to 1200s (from 300s). Although, for some reason the `kuberay-cluster` helm chart release is not waiting for all resources to be ready:
```
...
module.kuberay-cluster.helm_release.ray-cluster: Creation complete …
```

Downgrade RAG to 1.28; bump GMP resource creation delay; increase Ray worker creation timeout

---

modules/cloudsql/main.tf

based on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network#attributes-reference 
compute_network.id will always be projects/{{project}}/global/networks/{{name}}
if we use data "google_compute_network" to retrieve the resource, it will trigger cloudsql re-creation while the network is not changed.
test:
before: run terraform re-apply immediate after first time apply
- result https://paste.googleplex.com/5737676939984896#l=542
> Plan: 1 to add, 4 to change, 1 to destroy.
after: run terraform re-apply immediate after first time apply
- result https://paste.googleplex.com/6438789280432128
> Plan: 0 to add, 4 to change, 0 to destroy

concat private network intead of retrieving the data

---

modules/kuberay-operator/kuberay-operator-autopilot-values.yaml
modules/kuberay-operator/kuberay-operator-values.yaml
modules/kuberay-operator/kuberay.tf

So that kuberay resources are scoped to only the namespaced used in the terraform deployment

use single namespace installation for kuberay-operator

---

modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
modules/jupyter/jupyter_config/config-selfauth.yaml

Fixes https://github.com/GoogleCloudPlatform/ai-on-gke/issues/428
When using GCSFuse to back notebook data, JupyerHub is configured to use buckets named `gcsfuse-{username}`. This doesn't work because the bucket with that name is not created as part of any of our guides and the google service account does not have permissions to access those buckets. The buckets may also not be available because they're not unique.
This PR updates the ephemeral GCSFuse mounts to use the same GCS bucket created in the terraform module. It also configures the GCSFuse mount to use a subdirectory in the bucket `notebooks/{username}`.

JupyterHub should use a GCS bucket it can access when using GCSFuse

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py

I noticed 99th% request time was 60s in locust metrics.
Discovered there's an additional timeout variable we have to set, the network_connection timeout.
Related docs show this timeout is also default 60s
https://docs.locust.io/en/stable/increase-performance.html#fasthttpuser-class
Upped this to be the same as connection_timeout. Validated that locust max percentile goes beyond 60s.

fix timeout request issue in locust benchmark

---

applications/rag/frontend/main.tf

Please also test on your local: `kubectl set image deployment/rag-frontend  rag-frontend=us-central1-docker.pkg.dev/ai-on-gke/rag-on-gke/frontend@sha256:bc36e823a0110a65dae6336e3d46a03b798a6d396ba305a6590ae4bb8f895861 -n rag`
Tested-by: zlq

Update frontend image

---

applications/rag/frontend/main.tf

Please also test on your local: `kubectl set image deployment/rag-frontend  rag-frontend=us-central1-docker.pkg.dev/ai-on-gke/rag-on-gke/frontend@sha256:bc36e823a0110a65dae6336e3d46a03b798a6d396ba305a6590ae4bb8f895861 -n rag`
Tested-by: zlq

[release 1.1 cherry pick] Update frontend image (#480)

---

benchmarks/infra/stage-1/modules/gke-infra/cluster.tf

Was broken by https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/commit/f487b27aa9f424c005d1d2177eea1487770cc235

Fix spelling of default_nodepool

---

infrastructure/variables.tf

Because Autopilot doesn't support L4 GPUs in 1.27

default all clusters to use v1.28

---

applications/jupyter/main.tf
applications/rag/main.tf
applications/ray/main.tf
cloudbuild.yaml
infrastructure/tfvars_tests/standard-gke-public.platform.tfvars
modules/kuberay-monitoring/main.tf

- Fix project service dependency
- Switch cloudbuild test to create_network

Fix project service dependency

---

tutorials-and-examples/workflow-orchestration/dws-examples/README.md
tutorials-and-examples/workflow-orchestration/dws-examples/job.yaml

Update DWS example to contain maxRunDurationSeconds annotation in the Job definition

Update DWS example to contain maxRunDurationSeconds annotation in the Job definition

---

tpu-provisioner/internal/cloud/gke.go
tpu-provisioner/internal/controller/creation_controller.go
tpu-provisioner/internal/controller/deletion_controller.go

Rapid JobSet restarts can trigger concurrent node pool creations for the same logical Job. This PR adds in-memory de-duplication of those scenarios.
Also: Reduce some noisy reconciles that occur when node pools are deleting.

tpu-provisioner - Dedup NP creations on job-key and reduce noisy node pool deletion reconciles

---

benchmarks/benchmark/tools/locust-load-inference/README.md
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/custom_metric_aggregator.py
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py
benchmarks/benchmark/tools/locust-load-inference/main.tf
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-master-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-worker-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/variables.tf

custom_messages has bug that causes locust worker restarts. https://github.com/locustio/locust/issues/2608
We rely on custom messages for our custom metrics csv file periodic writes.
Since we've added in exporting the custom metrics to prometheus, I don't think we need the csv file write. The locust runner includes these metrics in its final report. And metrics are viewable via custom dashboards in cloud monitoring.
Rather than trying to make the heartbeat work, I think we should remove the csv file support and migrate to improving the total report that includes locust and GPU metrics as well.
This change also enables custom metrics for all workloads.

remove csv file write

---

benchmarks/benchmark/tools/locust-load-inference/README.md
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/requirements.txt
benchmarks/benchmark/tools/locust-load-inference/main.tf
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-worker-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/variables.tf

Additionally, changed how it does use one to be identical to tgi, including using secret manager (rather than a k8s secret, which would end up being stored in tf state.)
Also bump version of transformers to support google/gemma-2b

Alter locust to not require a hf token

---

benchmarks/benchmark/tools/locust-load-inference/README.md
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/requirements.txt
benchmarks/benchmark/tools/locust-load-inference/main.tf
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-worker-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/variables.tf

Additionally, changed how it does use one to be identical to tgi, including using secret manager (rather than a k8s secret, which would end up being stored in tf state.)
Also bump version of transformers to support google/gemma-2b

Alter locust to not require a hf token (#534)

---

benchmarks/infra/stage-2/modules/gke-setup/modules/gcs-fuse/main.tf
benchmarks/infra/stage-2/modules/gke-setup/modules/output-benchmark/main.tf
benchmarks/infra/stage-2/modules/gke-setup/modules/secret-manager/csi-driver-gcp-plugin/provider-gcp-plugin.yaml
benchmarks/infra/stage-2/modules/gke-setup/modules/secret-manager/main.tf
benchmarks/infra/stage-2/modules/gke-setup/modules/workload-identity/gcp.tf

Set stage-2 gcp modules to be fixed at stable version. Avoid any breaking changes to main.
Fix tolerations in csi-driver-gcp-plugin. Enables pod to be scheduled on every node (required for secret manager to work properly).
Toleration matches the tolerations in the other similar infra daemonsets, eg. https://github.com/GoogleCloudPlatform/ai-on-gke/blob/494b866d04d234654913f6e2e6a7b53f6d8e0688/benchmarks/infra/stage-2/modules/gke-setup/modules/secret-manager/csi-driver/secrets-store-csi-driver.yaml#L140

fix versions in stage-2. Fix toleration on csi-driver-gcp-plugin.

---

modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
modules/jupyter/jupyter_config/config-selfauth.yaml

This storage profile has a bunch of issues at the moment and not widely used. Removing for now to avoid confusion

Remove GCSFuse storage profile for JupyterHub notebook servers

---

applications/rag/variables.tf
applications/rag/workloads.tfvars

This allows creating Ray and Jupyter applications in the same project, and also doesn't accidentally delete SAs for the wrong deployment during tf destroy.

Use different SA names for Ray, Jupyter and RAG

---

modules/kuberay-monitoring/main.tf

The bump to 30 seconds reduced flakiness to nearly zero cases over the last 5 days. Doubling to 60 seconds to ensure we don't hit this during demo season. We already have a long-term fix underway to replace this.

Bump GMP delay to 60 seconds

---

cloudbuild.yaml

We recently introduced vector embedding generation and prompts in the RAG tests. This has been a little flakey so marking optional for now while we deflake it.

Mark RAG vector embedding and prompt tests as optional

---

applications/jupyter/metadata.yaml
applications/jupyter/variables.tf
applications/rag/frontend/main.tf
applications/rag/frontend/variables.tf
applications/rag/main.tf
applications/rag/metadata.yaml
applications/rag/variables.tf
applications/ray/metadata.yaml
modules/jupyter/main.tf
modules/jupyter/variables.tf
modules/kuberay-cluster/main.tf
modules/kuberay-cluster/variables.tf
tutorials-and-examples/hf-tgi/main.tf
tutorials-and-examples/hf-tgi/variables.tf

Update list(string) for additional_labels variable type to string because of a bug with marketplace support with list(string) type.
Using string to addtional_labels in string format, refer example - "created-by=gke-ai-quick-start-solutions,ai.gke.io=rag"

Move additional_labels to string for MP

---

applications/ray/kuberay-tpu-webhook/go.mod
applications/ray/kuberay-tpu-webhook/go.sum
applications/ray/kuberay-tpu-webhook/main.go
applications/ray/kuberay-tpu-webhook/webhook_main_test.go

This PR adds support for multiple worker groups that request TPUs (both single-host and multi-host) in the same Ray Cluster. This PR was tested by manually creating a RayCluster with single-host, multi-host, single-slice, and multi-slice worker groups and verifying that all were injected with the correct `TPU_NAME`, `TPU_WORKER_ID`, `replicaIndex`, and `TPU_WORKER_HOSTNAMES`.
This PR also adds unit tests for `getReplicaIndex` and `getNextWorkerID`, these tests can be run using `go test` from the applications/ray/kuberay-tpu-webhook folder.

Support for Multiple Separate TPU Worker Groups per RayCluster

---

cloudbuild.yaml
modules/kuberay-cluster/main.tf

RayCluster apply takes O(seconds). The actual ray worker deployment is done asynchronously by the ray operator.
Fixes https://github.com/GoogleCloudPlatform/ai-on-gke/issues/520

Remove timeout from RayCluster CR apply; bump CB timeout to mitigate stockouts

---

applications/ray/kuberay-tpu-webhook/Makefile
ray-on-gke/guides/tpu/README.md

This PR changes the `make install-cert-manager` command to one that works for both GKE standard and autopilot clusters. The previous `kubectl apply` command to install cert-manager is incompatible with GKE autopilot since the default `global.leaderElection.namespace` is a managed namespace on autopilot.
This PR was tested by installing cert-manager using the helm commands on both standard and autopilot clusters and verifying that the webhook was successfully issued a certificate.

Update webhook cert-manager install to work with GKE autopilot clusters

---

cloudbuild.yaml
modules/kuberay-cluster/main.tf

Remove timeout from RayCluster CR apply; bump CB timeout to mitigate stockouts (#576)
RayCluster apply takes O(seconds). The actual ray worker deployment is done asynchronously by the ray operator.

Cherrypick AP cloud build stockout mitigation onto release-1.1

---

tpu-provisioner/internal/cloud/gke.go

Add support for auto-provisioning of spot node pools.
Pod spec should include a node selector and tolerations:
```yaml
nodeSelector:
cloud.google.com/gke-spot: "true"
```
```yaml
tolerations:
- key: cloud.google.com/gke-spot
operator: Equal
value: "true"
effect: NoSchedule
```

tpu-provisioner: Add support for Spot Node Pools

---

tutorials-and-examples/workflow-orchestration/dws-examples/job.yaml

We are including this example in tutorials (https://cloud.devsite.corp.google.com/kubernetes-engine/docs/how-to/provisioningrequest#run_your_job). To enable the node pool name to be displayed as an editable variable in the tutorial I need to reformat it here.
Node pool is not defined in this example (it is only referenced) so the user might want to use any name. Having a placeholder makes it clearer.

Change nodepool name to a placeholder

---

applications/ray/kuberay-tpu-webhook/main.go

This PR removes an error returned by the validating admission webhook when a RayCluster is created with no workerGroupSpecs, making it pass-through for the RayCluster.
This PR has been tested with:

Ray TPU Webhook: Remove Error for nil workerGroupSpecs

---

tpu-provisioner/internal/controller/constants.go
tpu-provisioner/internal/controller/creation_controller.go
tpu-provisioner/internal/controller/creation_controller_test.go
tpu-provisioner/internal/controller/events.go
tpu-provisioner/internal/controller/pod_utils.go

This change ensures the TPU Provisioner creation controller only reconciles pods matching the following conditions:
- Part of a JobSet
- Leader pod (job completion index 0)
- Not yet scheduled
- Not marked for deletion
- Pod does not have label `tpu-provisioner.cloud.google.com/disable-autoprovisioning=true`

Add event filters for TPU Provisioner creation controller

---

applications/ray/kuberay-tpu-webhook/go.mod
applications/ray/kuberay-tpu-webhook/go.sum

This PR bumps the golang.org/x/net version to `v0.23.0` to fix a vulnerability detected in `v0.20.0`.
This PR has been tested with:

Fix golang.org/x/net Vulnerability

---

applications/jupyter/README.md
applications/jupyter/variables.tf
applications/jupyter/workloads.tfvars
infrastructure/README.md

Also add instructions to use a standard cluster if preferred.

Set the default GKE cluster type for jupyterhub to GKE Autopilot.

---

applications/rag/README.md
applications/rag/metadata.yaml
applications/rag/variables.tf
applications/rag/workloads.tfvars

Cherry-pick #635 to release-1.1 branch

Cherry-pick #635 to release-1.1 branch

---

tpu-provisioner/Dockerfile
tpu-provisioner/go.mod

This PR fixes container image build errors:
- Remove `-mod=vendor` from build command in Dockerfile since we removed vendor files in #614 
- Fix Go version format

[TPU Provisioner] Fix dockerfile and bump go to 1.22

---

tpu-provisioner/internal/cloud/gke.go
tpu-provisioner/internal/cloud/gke_test.go

This change will pass the ICI resiliency label (cloud.google.com/gke-tpu-ici-resiliency) to node pool creation request if pod has such node selector specified.

Pass ICI Resiliency label to Node Pool Creation Request

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/run.sh
benchmarks/benchmark/tools/locust-load-inference/main.tf
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-master-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/manifest-templates/locust-worker-controller.yaml.tpl
benchmarks/benchmark/tools/locust-load-inference/sample-terraform.tfvars

Small fix for hardcoded request type in locust - plumbs variable through and adds extra logging in run.sh.
Currently under e2e validation

fix hardcoded request type

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/run.sh
benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py
benchmarks/benchmark/tools/locust-load-inference/sample-terraform.tfvars

A few additional fixes required for http route
Tested end to end, validated locust comes up, and successful response.
Updates:
- remove single ' in run.sh
- remove self. references to methods that no longer belong to http user class
- update recommended defaults in sample tfvars file to work for tgi http

few small fixes for http tgi route

---

tpu-provisioner/README.md

- Remove old diagram which uses a Job instead of JobSet
- Update instructions to use static cluster version

[TPU Provisioner] Remove old diagram; use static cluster version

---

modules/kuberay-cluster/main.tf

`gmp-system` is the namespace for GKE Standard clusters and `gke-gmp-system` for Autopilot clusters. Both are needed to make GMP working in different clusters.

[FIX] add GKE standard cluster GMP namespace to networkpolicy

---

applications/jupyter/variables.tf
applications/rag/variables.tf
applications/ray/variables.tf
infrastructure/platform.tfvars

We currently enable image streamign for GPU node pools but not CPU node pools. Not sure why we only enabled it for GPU node pools but it probably makes sense to enable for all node pools by default. 
Fixes https://github.com/GoogleCloudPlatform/ai-on-gke/issues/509

Enable image streaming by default for CPU pools

---

benchmarks/benchmark/tools/locust-load-inference/locust-docker/locust-tasks/tasks.py
tutorials-and-examples/inference-servers/checkpoints/README.md
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh
tutorials-and-examples/inference-servers/jetstream/http-server/Dockerfile
tutorials-and-examples/inference-servers/jetstream/http-server/http_server.py
tutorials-and-examples/inference-servers/jetstream/maxtext/maxengine-server/Dockerfile
tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/checkpoint-job.yaml
tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/deployment.yaml
tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server/Dockerfile

Note: the `text_content=jetstream_pb2.DecodeRequest.TextContent(text=request.prompt)` change fixes a Jetstream change that broke making requests to the endpoint, the issue around decoding responses still exists, more to do there.

Bump Jetstream, maxtext, jetstream-pytorch versions in Jetstream inference server guide

---

benchmarks/inference-server/vllm/main.tf
benchmarks/inference-server/vllm/manifest-templates/vllm.tftpl
benchmarks/inference-server/vllm/variables.tf

Per https://docs.vllm.ai/en/latest/serving/metrics.html, openai api server supports vLLM serving metrics by default. This PR therefore:
- updates api server from vanilla to openai mode
- adds `swap_space` argument suggested in vLLM [benchmarks](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py#L6)
e2e tests with model `meta-llama/Llama-2-7b-chat-hf`. After [terraform apply](https://github.com/GoogleCloudPlatform/ai-on-gke/tree/main/benchmarks/inference-server/vllm#step-4-terraform-initialize-plan-and-apply):
```
$ VLLM_EXTERNAL_IP=`kubectl -n benchmark get service vllm -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`
$ curl $VLLM_EXTERNAL_IP/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "meta-llama/Llama-2-7b-chat-hf",
"prompt": …
```

Support vllm openai api server

---

benchmarks/infra/stage-2/modules/gke-setup/modules/nvidia-dcgm/manifest-templates/03-cm-dcgm.yaml

Small change to add a few missing DCGM metrics

add missing dcgm metrics

---

modules/custom-metrics-stackdriver-adapter/README.md
modules/custom-metrics-stackdriver-adapter/main.tf
modules/custom-metrics-stackdriver-adapter/templates/apiservice_v1beta1.custom.metrics.k8s.io.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/apiservice_v1beta1.external.metrics.k8s.io.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/apiservice_v1beta2.custom.metrics.k8s.io.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/clusterrole_custom-metrics-resource-reader.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/clusterrolebinding_custom-metrics-resource-reader.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/clusterrolebinding_custom-metrics:system:auth-delegator.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/clusterrolebinding_external-metrics-reader.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/deployment_custom-metrics-stackdriver-adapter.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/rolebinding_custom-metrics-auth-reader.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/templates/service_custom-metrics-stackdriver-adapter.yaml.tftpl
modules/custom-metrics-stackdriver-adapter/variables.tf

Added Custom Metrics Stackdriver Adapter module in subfolder of the lowest common parent folder (./modules)

Custom Metrics Stackdriver Adapter Module

---

applications/rag/variables.tf
applications/ray/variables.tf
modules/kuberay-cluster/values.yaml

Enable Ray Autoscaler for the Rag example application. Tested with both GKE Autopilot cluster and Standard cluster with Cluster Autoscaler.

Enable Ray Autoscaler for the Rag example application

---

tutorials-and-examples/inference-servers/checkpoints/Dockerfile
tutorials-and-examples/inference-servers/checkpoints/README.md
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh
tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server/Dockerfile
tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/README.md
tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/checkpoint-job.yaml
tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/deployment.yaml
tutorials-and-examples/inference-servers/jetstream/pytorch/single-host-inference/pd-deployment.yaml

This PR adds the following support:
1. HuggingFace CLI support in checkpoint conversion script
2. Checkpoint conversion support for Llama-2, Llama-3, and Gemma models in JetStream Pytorch
4. Enables quantization checkpoint conversion
5. Enables tokenizer.model upload to GSBucket
6. Adds / renames arguments to checkpoint conversion script

Add HuggingFace support for automated inference checkpoint conversion

---

modules/jetstream-maxtext-deployment/main.tf
modules/jetstream-maxtext-deployment/templates/custom-metrics-stackdriver-adapter/hpa.jetstream.yaml.tftpl
modules/jetstream-maxtext-deployment/templates/prometheus-adapter/hpa.jetstream.yaml.tftpl
modules/jetstream-maxtext-deployment/variables.tf
tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/README.md
tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/terraform/sample-terraform.tfvars
tutorials-and-examples/inference-servers/jetstream/maxtext/single-host-inference/terraform/variables.tf

Having multiple HPAs monitoring the same resource causes a race condition. Keeping all the rules in the same HPA fixes this.

Jetstream Maxtext Deployment Module: All scale rules now in a single HPA

---

ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
ray-on-gke/tpu/kuberay-tpu-webhook/main.go
ray-on-gke/tpu/kuberay-tpu-webhook/webhook_main_test.go

This PR adds support for autoscaling RayClusters by generating `TPU_WORKER_HOSTNAMES` when intercepting each Pod, rather than when intercepting the RayCluster CR.
This PR has been tested as follows:

Ray TPU Webhook Autoscaling Support

---

tutorials-and-examples/workflow-orchestration/dws-examples/dws_and_reservation.yaml
tutorials-and-examples/workflow-orchestration/dws-examples/job-without-node-selector.yaml

Added Kueue exemplary setup which uses reservation nodepool first, and if there is no capacity in reservation, then tries DWS.

Add Kueue exemplary setup for reservation and DWS

---

benchmarks/inference-server/text-generation-inference/main.tf
benchmarks/inference-server/text-generation-inference/manifest-templates/text-generation-inference.tftpl
benchmarks/inference-server/text-generation-inference/variables.tf

This change adds quantization support so we can use quantization techniques like eetq, bitsandbytes, etc. when deploying models using TGI. It allows us to benchmark models like Llama3 405B using FP8 too.

Add quantization support for TGI

---

ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
ray-on-gke/tpu/kuberay-tpu-webhook/deployments/deployment.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/Chart.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/values.yaml

This PR bumps the Ray TPU Webhook image to the latest release, `v1.2.0`. This PR also changes the docker repository used to `us-docker.pkg.dev/ai-on-gke/kuberay-tpu-webhook/tpu-webhook`, the repository built to by the automated pipeline.

Bump Ray TPU Webhook Image

---

modules/jetstream-maxtext-deployment/templates/custom-metrics-stackdriver-adapter/hpa.jetstream.yaml.tftpl
modules/jetstream-maxtext-deployment/templates/prometheus-adapter/values.yaml.tftpl

Reconfigured Jetstream HPA resources to use TPU metrics scraped from PodMonitoring instead of TPU metrics collected by GMP

Change TPU Metrics Source for Autoscaling

---

applications/rag/main.tf
applications/ray/main.tf
modules/kuberay-operator/kuberay.tf
modules/kuberay-operator/variables.tf

Move provisioning service accounts away from kuberay-operator module. These two are different tasks and after we use ray addon, we will not install kuberay-operator module in applications.

Refactor: move workload identity service account out of kuberay-operator

---

benchmarks/inference-server/text-generation-inference/hpa-templates/dcgm-podmonitoring.yaml.tftpl
benchmarks/inference-server/text-generation-inference/monitoring-templates/tgi-podmonitoring.yaml.tftpl
benchmarks/infra/stage-2/modules/gke-setup/modules/nvidia-dcgm/manifest-templates/02-ds-exporter.yaml

Decrease scrape interval of metrics from TGI and DCGM from 30s to 15s in benchmark, this will allow for quicker autoscaling and also for better graphs when plotting the data.
To do this, we need to export data out of DCGM more often (here I have it set to 5s by setting the [`collect-interval`](https://github.com/NVIDIA/dcgm-exporter/blob/6d499c68a93677e8ccafe857427b09d4617ebfae/pkg/cmd/app.go#L56) flag).

Decrease scrape interval of metrics from TGI and DCGM to 15s in benchmark

---

cloudbuild.yaml

The ray application is quite flaky with the following error, adding sleep to wait for pods to be more stable.
Forwarding from 127.0.0.1:8265 -> 8265
Handling connection for 8265
E0828 07:18:32.742675     386 portforward.go:409] an error occurred forwarding 8265 -> 8265: error forwarding port 8265 to pod 3f1f339204911c524c01d65e02ec3e19e20b2c3fdb5dcbb900d80be80ba97a11, uid : failed to execute portforward in network namespace "/var/run/netns/cni-a9192461-40d0-574a-1a1a-756308c62f70": failed to connect to localhost:8265 inside namespace "3f1f339204911c524c01d65e02ec3e19e20b2c3fdb5dcbb900d80be80ba97a11", IPv4: dial tcp4 127.0.0.1:8265: connect: connection refused IPv6 dial tcp6 [::1]:8265: connect: cannot assign requested address 
error: lost connection to pod

fix: add delays in ray application cloud build test

---

cloudbuild_cleanup.yaml

Fix the script to delete leftover VPCs, which only deletes firewall before the fix. 
However, to delete a VPC, the linked subnets, firewall, address, peering, route have to be deleted first.
In addition, instead of using inline YAML in gcp console to define the cloud build job, move the script to this repo. 
1. Safer and protect us from accidentally delete the inline script. 
2. Requires code review to change the definition in production.

fix: add vpc cleanup cloudbuild yaml

---

tutorials-and-examples/hf-tgi/README.md
tutorials-and-examples/hf-tgi/cloudbuild.yaml
tutorials-and-examples/hf-tgi/main.tf
tutorials-and-examples/hf-tgi/workloads.tfvars

Create e2e test for hg-tgi tutorial. 
Since the underlying inference-service module already has test coverage via the standard PR trigger, this e2e test is configured to run only under the following conditions:
1. When there are changes in the tutorials-and-examples/hf-tgi directory, excluding .md files. 
2. The standard PR trigger e2e test is not required if all changes are limited to tutorials-and-examples/hf-tg directory.

fix: add e2e test for hg-tgi

---

tutorials-and-examples/gpu-examples/training-single-gpu/src/tensorflow-mnist-example/tensorflow_mnist_batch_predict.py
tutorials-and-examples/gpu-examples/training-single-gpu/src/tensorflow-mnist-example/tensorflow_mnist_train_distributed.py

Due to [Keras is upgraded to 3 after TF 2.16](https://blog.tensorflow.org/2024/03/whats-new-in-tensorflow-216.html), the single GPU job is broken. 
This PR is to fix the issue.

[FIX] Single GPU training job update

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/sample.tfvars
benchmarks/inference-server/vllm/manifest-templates/vllm.tftpl

Currently the benchmarking script only works with the regular entrypoint of vllm. Since the benchmarking suite builds uses openai entrypoint instead, changed it to support that entrypoint
.

Adding support vLLM openai entrypoint benchmarking script

---

benchmarks/benchmark/tools/profile-generator/container/requirements.txt
benchmarks/inference-server/vllm/main.tf
benchmarks/inference-server/vllm/manifest-templates/vllm.tftpl
benchmarks/inference-server/vllm/monitoring-templates/vllm-podmonitoring.yaml.tftpl

scraped vllm metrics to cloud monitoring
small fix on vllm PORT var -> VLLM_PORT
small fix for this numpy error that showed up in logs:
"A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2."

add podmonitoring to vllm, small fix

---

benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/sample.tfvars

- wait to finish latest build before deploying manifests - fixes any issues seen with latest container not being deployed when expected.
- update sample.tfvars to ensure build happens first try

update lpg to deploy latest build on new build

---

cloudbuild.yaml

This is so that we can make logs for CI visible to non-Googlers that don't have access to the cloud build dashboard.
Work on #786.

Set an explicit logs bucket in the cloud build.

---

best-practices/gke-batch-refarch/02_platform/monitoring/deploy-dashboard.yaml
best-practices/gke-batch-refarch/02_platform/monitoring/kueue-dashboard.json

Adding a Grafana monitoring chart with GKE nodes types (reserved, spot, on-demand)

Adding a Grafana monitoring chart with GKE nodes types (reserved, spot, on-demand)

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py

Modify the serving benchmark to write json output similar to Jetstream benchmark: https://github.com/richardsliu/JetStream/blob/vllm-benchmark/benchmarks/benchmark_serving.py#L648
This will allow the benchmark to integrate with XLML dashboard.

Allow benchmark to write json output

---

infrastructure/versions.tf
modules/gke-autopilot-private-cluster/main.tf
modules/gke-autopilot-public-cluster/main.tf
modules/gke-standard-private-cluster/main.tf
modules/gke-standard-public-cluster/main.tf

Upgrade gke submoduel version to patch the fix in latest release
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/releases/tag/v33.0.0

fix: upgrade gke module to avoid TPGv5.44.0 with Autopilot

---

benchmarks/benchmark/tools/profile-generator/README.md
benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/container/requirements.txt
benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/variables.tf
benchmarks/benchmark/tools/profile-generator/variables.tf

Add initial implementation for scraping server side metrics for analysis.
Initial implementation includes support for vLLM and Jetstream.
Validated end to end, example output at end of output file:
```
Metric Name: vllm:gpu_cache_usage_perc
Mean: 0.6996527777777777
Median: 0.8744212962962963
Min: 0.05439814814814814
Max: 0.9953703703703703
P90: 0.9936342592592593
P99: 0.9951967592592592
Metric Name: vllm:num_requests_waiting
Mean: 25.75
Median: 2.5
Min: 0
Max: 98
P90: 70.10000000000002
P99: 95.20999999999998
```

Add server metrics promql scraping

---

benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl

Two things preventing collecting results:
- LPG is a Job so pod dies immediately after command finishes, changed to Deployment prevent this.
- `--save-json-results` is not enabled by default, changed to enabled by default

Make LPG results collectable

---

scripts/network-setup/v6e-network-optimization.yaml

This worked internally but does not seem to be working when pulling the script via kubectl.
EDIT: to clarify, it *used to* work internally, but does not anymore. This proposed fix has been verified to work and should be more stable.

Updating the pause container image location.

---

applications/rag/main.tf
applications/ray/main.tf
infrastructure/tfvars_tests/standard-gke-public.platform.tfvars
infrastructure/versions.tf

The pinged version has reached to REGULAR channel. 
The default GKE version used in our TF is 1.30, which will pick the highest version in REGULAR channel.

fix: remove gke cluster version

---

benchmarks/inference-server/vllm/hpa-templates/hpa.vllm.custom_metric.yaml.tftpl
benchmarks/inference-server/vllm/main.tf
benchmarks/inference-server/vllm/sample-terraform.tfvars
benchmarks/inference-server/vllm/variables.tf

Add automatic deployment of cmsa and autoscaling config for custom metrics with vllm

enable vllm autoscaling with cmsa

---

tpu-provisioner/cmd/main.go
tpu-provisioner/internal/cloud/common.go
tpu-provisioner/internal/cloud/gke.go
tpu-provisioner/internal/cloud/gke_context.go
tpu-provisioner/internal/cloud/gke_test.go

Copy configured Pod labels to Node config at Node Pool creation-time.
Configured via `GCP_POD_TO_NODE_LABELS`, a comma-separated list of label keys.
```bash
GCP_POD_TO_NODE_LABELS=abc,xyz go run ./cmd/main.go
2024-08-28T17:55:00-04:00       INFO    setup   creating gke client     {"project": "", "clusterLocation": "", "cluster": "", "zone": "", "nodeServiceAccount": "", "nodeTags": [], "podToNodeLabels": ["abc", "xyz"]}
2024-08-28T17:55:00-04:00       INFO    setup   starting manager
```

Allow TPU Provisioner to be configured to copy Pod labels to Node labels

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl

Example LPG json results, a few notes:
- TPOT metric is faulty and incorrectly records `inf` to buckets
- Some values are duplicated across various fields. This is intentional. This json is expected to be consumed by various pipelines, each expecting uniformity.
```
{
"metrics": {
"num_prompts": 600,
"request_rate": 20,
"server_metrics": {
"jetstream_slots_used_percentage": {
"Mean": "0.81875",
"Median": "1",
"Std": "0.3625",
"Min": "0.09375",
"Max": "1",
"P90": "1",
"P99": "1"
},
"jetstream_prefill_backlog_size": {
"Mean": "66.75",
"Median": "75",
"Std": "44.71786555729153",
"Min": "0",
"Max": "117",
"P90": "110.7",
"P99": "116.36999999999999"
},
"jetstream_time_to_first_token": {
"Mean": "0.129368504891402",
"Median": "0.1624223602484472",
"Min": "0.01",
"Max": "0.25",
"P90": …
```

More metrics on LPG script

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py

[PR #832 ](https://github.com/GoogleCloudPlatform/ai-on-gke/pull/832) introduced a bug where the folllowing keys werent set on 'metrics', this PR fixes this.
```
"benchmark_time": 44.91958165168762,
"total_output_token": 58986,
"output_tokens_per_min": 78788.80145062602,
"total_input_tokens": 39871,
"input_tokens_per_min": 53256.506673412514,
"total_tokens": 98857,
"tokens_per_min": 132045.30812403854,
"avg_latency": 7.175992427666982,
"avg_per_token_latency": 0.06020041991300422,
"avg_per_output_token_latency": 0.35792783426739533,
"avg_input_len": 66.45166666666667,
"avg_output_len": 98.31
```
Example fixed output JSON:
```
{
"metrics": {
"num_prompts": 600,
"request_rate": 20,
"server_metrics": {
"jetstream_slots_used_percentage": {
"Mean": "0.80625",
"Median": "1",
"Std": "0.3875", …
```

Missing JSON fields

---

benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/sample.tfvars
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/variables.tf
benchmarks/benchmark/tools/profile-generator/sample.tfvars
benchmarks/benchmark/tools/profile-generator/variables.tf

This change makes the benchmark time configurable so it makes it easy to tweak it and identify when we reach steady state. This change also increases the default time from 30 seconds to 2 minutes based on experimental data.

Make the benchmark time configurable and set default to 2 minutes

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py

Throughput was changed to be in rps from output tokens per second. We don't want this to be the default. So, fixing that.

Fix throughput to be in output tokens per second

---

tutorials-and-examples/inference-servers/checkpoints/Dockerfile
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh
tutorials-and-examples/inference-servers/jetstream/http-server/http_server.py
tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server/Dockerfile

Additionally updates healthcheck for HTTP server

JetStream checkpoint converter support for Llama models on MaxText

---

benchmarks/benchmark/tools/profile-generator/README.md
benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh

- Checkpoint conversion syntax correction
- LPG minor cosmetic corrections to README and benchmark_serving
Currently the outputs for ms/req and ms/output_token are: 
```
Average Average milliseconds/request (includes waiting time on server): 132953.99
Average Average milliseconds/output_token (includes waiting time on server): 5937.29
```

minor cosmetic updates to lpg and checkpoint conversion syntax

---

benchmarks/inference-server/text-generation-inference/manifest-templates/text-generation-inference.tftpl
modules/inference-service/main.tf
tutorials-and-examples/genAI-LLM/deploying-mistral-7b-instruct-L4gpus/README.md
tutorials-and-examples/genAI-LLM/deploying-mistral-7b-instruct-L4gpus/mistral-7b.yaml
tutorials-and-examples/genAI-LLM/deploying-mixtral-8x7b-instruct-L4-gpus/README.md
tutorials-and-examples/genAI-LLM/deploying-mixtral-8x7b-instruct-L4-gpus/mixtral-8x7b.yaml
tutorials-and-examples/genAI-LLM/serving-llama2-70b-on-l4-gpus/README.md
tutorials-and-examples/genAI-LLM/serving-llama2-70b-on-l4-gpus/text-generation-interface.yaml

This PR updates a bunch of outdated references to Text Generation Inference (TGI) container, as previously those were pointing to the GitHub Container Registry where Hugging Face publishes those containers i.e. ghcr.io/huggingface/text-generation-inference; but since the Hugging Face DLCs on Google Cloud were recently released publicly (see [`Google-Cloud-Containers`](https://github.com/huggingface/Google-Cloud-Containers)), now those references have been updated to point to the DLCs hosted on Google Cloud's Artifact Registry.
cc @brandonroyal

Update references to Hugging Face DLC for TGI

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/variables.tf
benchmarks/benchmark/tools/profile-generator/variables.tf

This is useful for benchmarking multiple LoRA adapters. I used this to [benchmark the gateway](https://docs.google.com/document/d/11ALHEF-9yOaLdbHbDjBoTY6fzejoEKiSYHzWpWqe8ZY/edit#heading=h.bow7ai44ybg5): 
- Also fix the latency_throughput_curve.sh to parse non-integer request rate properly.
- Also added "errors" to the benchmark results.

Add the ability to benchmark multiple models concurrently

---

tutorials-and-examples/models-as-oci/Dockerfile
tutorials-and-examples/models-as-oci/README
tutorials-and-examples/models-as-oci/cloudbuild.yaml

This is a tutorial on how to package models and low rank adapters from huggingface as images, push them to Artifact registry and consume in GKE deployments

Package model weights and lora adapters as images to deploy in GKE

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/requirements.txt
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator-podmonitoring.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl

- Added a Prometheus server running on port 9090
- Added the `LatencyProfileGenerator:prompt_length`, `"LatencyProfileGenerator:response_length`, and `LatencyProfileGenerator:time_per_output_token` metrics.
- Added PodMonitoring resource in Terraform automation.
Example results in GMP:

Added Prometheus Server to LPG

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py

The following was run to test:
```
python3 benchmark_serving.py --scrape-server-metrics --save-json-results --host=llama3-8b-vllm-service --model=meta-llama/Meta-Llama-3-8B --dataset=ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer=meta-llama/Meta-Llama-3-8B --request-rate="10" --backend=vllm --num-prompts=100 --max-input-length=256 --max-output-length=256 --port=8000
```
Results observed in metrics explorer:
cs explorer:
Note GMP doesn't collect metrics frequently enough to capture decreasing metrics, this was validated manually

Add active requests Prometheus Metric

---

applications/rag/README.md
applications/rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb

In the example Rag application, the Ray job takes hours to finish. The tasks that generates the vector embedding finished in minutes but the Ray job keeps running and only performs tasks `_StatsActor.get_datasets` and `AutoscalingRequester.purge_expired_requests` for hours, which seems useless. 
This PR explicitly shutdown the ray job immediately after the generating vector embedding task finishes. And update README accordingly.
Tested in my local setup. The output of the last cell looks right.
```
print query_results, the 1st one is the hit
('57219b18-e5df-4366-a9b3-852083418346', 'This is a Movie in Argentina, Italy called Food on the Go added at May 16, 2018 whose director is Mercedes Cordova and with cast:  released at 2017.  ... (70 characters truncated) ... reans and experts trace …
```

explicitly shutdown ray job after generating vector embedding

---

best-practices/startup-latency.md

- Use secondary boot disk
- Use persistent disk for model weights loading

Add two more things about shortening startup latency

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/container/requirements.txt
benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/variables.tf
benchmarks/benchmark/tools/profile-generator/variables.tf

Added the following two flags to benchmark_serving.py:
- `--output-bucket`: upload results in json format to this bucket
- `--output-bucket-filepath`: if specified, upload results to this path within bucket, otherwise upload to root
Requisite changes to terraform also included

GCS Bucket upload support

---

benchmarks/benchmark/tools/profile-generator/build.tf
benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh
benchmarks/benchmark/tools/profile-generator/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/main.tf
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/manifest-templates/latency-profile-generator.yaml.tpl
benchmarks/benchmark/tools/profile-generator/modules/latency-profile/variables.tf
benchmarks/benchmark/tools/profile-generator/variables.tf

Added new variable `stream_request` to determine whether or not to stream the request. Default value is false. Only vLLM is supported.
Also added TTFT metric.

Adding streaming support to the benchmarking script

---

benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh

Currently latency profile generator only waits 5 seconds between each request rate run. 
Model server metrics are pulled every 15 seconds.
To ensure isolation of model server metrics scraped between each request rate run, wait 30 seconds. This allows related metrics to emit at least one "0" prior to the next run (which enables us to validate proper isolation).

wait 30 seconds between each request rate run

---

tutorials-and-examples/workflow-orchestration/dws-examples/dws-queues.yaml

Support workloads requesting ephemeral-storage, and match the ResourceFlavor in https://cloud.google.com/kubernetes-engine/docs/tutorials/kueue-intro#create_the_resourceflavor

Define ephemeral-storage in ClusterQueue

---

modules/jupyter/main.tf

Jupyterhub helm chart has a [new release](https://hub.jupyter.org/helm-chart/) on 11/07. After than, all rag e2e tests started [failing](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?query=trigger_id%3D%2266c7c11e-51cc-4b48-aca9-c1255f57958a%22&e=13803378&mods=getting_started_solutions_mock_data&project=gke-ai-eco-dev), which are caused by the below jupyterhub spawner error
```
2024-11-12 12:00:02.275 PST
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 12:00:02.275 PST
File "/usr/local/lib/python3.11/site-packages/kubespawner/spawner.py", line 1847, in <dictcomp>
2024-11-12 12:00:02.275 PST
return {k: self._expand_all(v) for k, v in src.items()}
2024-11-12 12:00:02.275 PST
^^^^^^^^^^^^^^^^^^^
2024-11-12 12:00:02.275 PST
File …
```

Fix the jupyter hub helm chart version to avoid using the latest one which introduce error whan spawn a server

---

scripts/network-setup/v6e-network-optimization.yaml

The container image contains the script, but makes future updates (if necessary) more straightforward by just pulling a new image rather than updating the sript inside the daemonset. The contents of the image also allow us to mount only /sys and /proc, instead of mounting / entirely.

Use the tpu_network_optimizer image instead of a raw bash script.

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py
tutorials-and-examples/inference-servers/jetstream/http-server/http_server.py

Example snippet of streamed responses with respective full response for 
```
curl --request POST --header "Content-type: application/json" -s localhost:8000/generate --data '{
"prompt": "What are the top 5 programming languages ",
"max_tokens": 100,
"stream": true
}'
```
```
b'{\n    "id": "generate-b1f2ac51319944658db3f65560881067",\n    "time_created": 1731094258.4464087,\n    "text": "\\n"\n}'
b'{\n    "id": "generate-2670cd56a9ef40d697c25959d1d46d31",\n    "time_created": 1731094258.4621747,\n    "text": "\\n"\n}'
b'{\n    "id": "generate-be55c20ad9914364813738c842e84ce6",\n    "time_created": 1731094258.4723089,\n    "text": "for"\n}'
b'{\n    "id": "generate-dfcc3e724129453c936d4bb24b892310",\n    "time_created": 1731094258.4828267,\n    "text": " data"\n}'
b'{\n    "id": …
```

Add HTTP streaming support for JetStream

---

ray-on-gke/tpu/kuberay-tpu-webhook/Troubleshooting.md
ray-on-gke/tpu/kuberay-tpu-webhook/main.go
ray-on-gke/tpu/kuberay-tpu-webhook/webhook_main_test.go

This PR adds a `sync.WaitGroup` object and integer `waiting` var to each `TPUWebhookServer` object. All goroutine calls to `mutatePod` now `Wait()` before listing from the PodInformer cache, or timeout after 1 second, and then increment the waiting var and call `wg.Add(1)`. `wg.Done()` is called by the `AddFunc` `EventHandler`, which indicates the PodInformer has updated with the last Pod admitted by that webhook replica. This ensures the PodInformer cache is available and updating prior to listing from the cache. To support multiple webhook replicas, `wg.Done()` is only called if the int `waiting` var on the `TPUWebhookServer` object is greater than 1. This allows the webhook to block on previous `TPUWebhookServer.Mutate` calls until the PodInformer cache updates at least once.  I also …

Fix Webhook Assigning Identical `TPU_WORKER_ID`s

---

ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
ray-on-gke/tpu/kuberay-tpu-webhook/deployments/deployment.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/Chart.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/values.yaml

The `v1.2.1` image contains a fix for inconsistent PodInformer updates resulting in incorrect `TPU_WORKER_ID`s for large TPU slice sizes.

Bump Ray TPU webhook image to v1.2.1

---

applications/rag/main.tf
modules/jupyter/jupyter_image/notebook_image/Dockerfile
modules/jupyter/jupyter_image/notebook_image/README.md
modules/jupyter/jupyter_image/notebook_image/cloudbuild.yaml
modules/jupyter/jupyter_image/notebook_image/requirements.txt

Add prefix `sample-public-image-` to the image tag to mitigate the internal vulnerability check. New tag has been added https://pantheon.corp.google.com/artifacts/docker/ai-on-gke/us-central1/rag-on-gke/jupyter-notebook-image?e=13803378&mods=getting_started_solutions_mock_data&project=ai-on-gke

Update the Jupyter notebook image version

---

tutorials-and-examples/skypilot/README.md
tutorials-and-examples/skypilot/launch.py
tutorials-and-examples/skypilot/text-classification/README.md
tutorials-and-examples/skypilot/text-classification/requirements.txt
tutorials-and-examples/skypilot/text-classification/run_classification.py
tutorials-and-examples/skypilot/text-classification/run_glue.py
tutorials-and-examples/skypilot/text-classification/run_glue_no_trainer.py
tutorials-and-examples/skypilot/text-classification/run_xnli.py
tutorials-and-examples/skypilot/train.yaml

Create the tutorial to demonstrate using SkyPilot to launch batch workload across regions.

skypilot tutorial

---

benchmarks/benchmark/tools/profile-generator/container/benchmark_serving.py

Extension of: https://github.com/GoogleCloudPlatform/ai-on-gke/pull/899
Before:
- TPOT (includes first token latency)
After:
- request_latency_per_output_token (includes first token latency)
- TPOT (does not include first token latency)

Split TPOT into two metrics, one with first token latency and one without

---

applications/jupyter/metadata.display.yaml
applications/jupyter/metadata.yaml
applications/rag/metadata.display.yaml
applications/rag/metadata.yaml
applications/ray/metadata.display.yaml
applications/ray/metadata.yaml

With the new GKE ML/AI UI, users of QSS don't need to go to the MP Solution deployment view page to view the deployment details. So remove the related acknowledge checkbox from the form.

Remove the acknowledge checkbox for solution_deployment_view

---

applications/rag/charts/gmp-engine/Chart.yaml
applications/rag/charts/gmp-engine/charts/gmp-frontend/Chart.yaml
applications/rag/charts/gmp-engine/charts/gmp-frontend/templates/deployment.yaml
applications/rag/charts/gmp-engine/charts/gmp-frontend/templates/service.yaml
applications/rag/charts/gmp-engine/charts/gmp-frontend/values.yaml
applications/rag/charts/gmp-engine/templates/podmonitoring.yaml
applications/rag/charts/gmp-engine/values.yaml
applications/rag/main.tf

When we release RAG QSS on Marketplace, we zip the whole rag folder and upload it to a GCS bucket so Marketplace can use it to do terraform apply. With the current setup to install `gmp-engine` for rag, the Marketplace will not be able to find the charts since it's not in the GCS. It is also not possible to modify the chart path to point to the github patch like what we do for the other modules in RAG, because it is not supported with the current setup of the `gmp-engine` chart. As a workaround, duplicating the charts to the rag folder so it can be zipped together and uploaded to GCS.

Duplicates charts to rag folder so the Marketplace release can work

---

tutorials-and-examples/skypilot/README.md

Escape the wildcard characters and fix a typo

fix formatting in tutorials-and-examples/skypilot/README.md

---

tutorials-and-examples/workflow-orchestration/dws-examples/dws-queues.yaml
tutorials-and-examples/workflow-orchestration/dws-examples/dws_and_reservation.yaml

Bump Kueue quotas to 1 billion per resource to provide almost unlimited admission

Improve examples for DWS-Kueue usage

---

security_test/allowlist/category/helm/iap/defaultnamespace.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/allowprivilegeescalation.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/capabilities.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/imagedigest.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/imagefreshness.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/imagepath.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/readonlyrootfs.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/rootless.json
security_test/allowlist/category/helm/kuberay-tpu-webhook/seccompprofile.json
violation_scan_helm.yaml

This PR initiates the integration of Shipshape security scans into the ai-on-gke repository, starting with Phase 1: Helm Scan Onboarding.
Purpose:
This PR introduces a Cloud Build workflow to automatically perform Helm scans on the ai-on-gke repository using the Shipshape validation service. This initial integration focuses on scanning Helm charts for the iap and kuberay-tpu-webhook components. These components were selected because they are owned and fully controlled by the ai-on-gke team and do not require a cluster scan.
Implementation:
A new Cloud Build configuration file violation_scan_helm.yaml is added to trigger Helm scans on pull requests.
The workflow utilizes a Docker image from the validation-service-agent repository to execute the scans.
The scan targets all Helm charts …

Integrating Shipshape with ai-on-gke: Helm Scan Integration

---

cloudbuild.yaml

The E2E test [failed](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?query=trigger_id%3D%227f679323-a550-4c58-9c6d-5ed9f52b75d2%22&e=13803378&hl=en&mods=getting_started_solutions_mock_data&project=gke-ai-eco-dev) because of timeout waiting for the Ray pod sometimes: `error: timed out waiting for the condition on pods/ray-cluster-kuberay-head-d4sn5
Pod(s) found in the namespace 'ml-450d0fa-5920027c-ray'.
Waiting for any pod to exist in the namespace 'ml-450d0fa-5920027c-ray' (timeout: 3000s)...`. Increasing the timeout as a mitigation.
I have tested it by pointing the previously failed build to my branch, and saw the recent two build all succeeded: https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?query=trigger_id%3D%227f679323-a550-4c58-9c6d-5ed …

Increase timeout to fix e2d flaky

---

infrastructure/variables.tf

Adds `queued_provisioning` setting on all node pools. This is required for DWS. 
See https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest

add queued_provisioning variable to all pools for infra module

---

benchmarks/benchmark/tools/profile-generator/container/latency_throughput_curve.sh

Tested the container e2e.
Yaml:
```
...
containers:
- command:
- bash
- -c
- ./latency_throughput_curve.sh
env:
- name: OUTPUT_LENGTH
value: '512'
- name: OUTPUT_BUCKET
value: 'my-bucket'
...
```
Log: Notice the `output-bucket` flag
`python3 benchmark_serving.py --save-json-results --host=model-server-service.benchmark-catalog.svc.cluster.local --port=8081 --dataset=ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer=meta-llama/Llama-2-7b-hf --request-rate=1 --backen │
│ d=vllm --num-prompts=10 --max-input-length=1024 --max-output-length=512 '--file-prefix=result/${ID}' --models=meta-llama/Llama-2-7b-hf --output-bucket=my-bucket --save-aggregated-result`
Yaml:
```
...
containers:
- command:
- bash
- -c
- ./latency_throughput_curve.sh
env:
- name: OUTPUT_LENGTH
value: '512'
...
``` …

Make GCS bucket optional

---

modules/inference-service/main.tf
tutorials-and-examples/genAI-LLM/deploying-mistral-7b-instruct-L4gpus/README.md
tutorials-and-examples/genAI-LLM/deploying-mistral-7b-instruct-L4gpus/mistral-7b.yaml
tutorials-and-examples/genAI-LLM/deploying-mixtral-8x7b-instruct-L4-gpus/README.md
tutorials-and-examples/genAI-LLM/deploying-mixtral-8x7b-instruct-L4-gpus/mixtral-8x7b.yaml
tutorials-and-examples/genAI-LLM/serving-llama2-70b-on-l4-gpus/README.md
tutorials-and-examples/genAI-LLM/serving-llama2-70b-on-l4-gpus/text-generation-interface.yaml

The current image override the HF_HOME to /tmp from /data. Even after changing the mountpath to /tmp there is some regression in the newer TGI image which results into out of GPU memory on L4 and requires atleast A2 node. Rolling back the image version to get the sample working will investigation happen in the background.
Issue: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/1581

Reverting the TGI image version for LLAMA multiple GPUs in GKE samples

---

tpu-provisioner/Dockerfile
tpu-provisioner/cloudbuild.yaml
tpu-provisioner/cmd/main.go
tpu-provisioner/go.mod
tpu-provisioner/internal/cloud/common.go
tpu-provisioner/internal/cloud/gke.go
tpu-provisioner/internal/cloud/gke_context.go
tpu-provisioner/internal/cloud/gke_test.go

Add v6e accelerator-awareness & account for `cloud.google.com/reservation-project` node selector.

TPU Provisioner: Add support for v6e & cross project reservations

---

ray-on-gke/tpu/kuberay-tpu-webhook/main.go
ray-on-gke/tpu/kuberay-tpu-webhook/webhook_main_test.go

This PR fixes a bug where the KubeRay RayCluster controller's truncation of generated service names ([here](https://github.com/ray-project/kuberay/blob/b753f1ad8b85e94003ed95dbbd75ff1a41d30570/ray-operator/controllers/ray/utils/util.go#L184)) resulted in incorrectly generated `TPU_WORKER_HOSTNAMES`. This bug was discovered because RayJobs and RayServices with names > 13 chars result in long generated RayCluster names and a truncated TPU headless worker service name. This PR applies the same truncation when generating the name within the webhook so that the names remain consistent.
Related Issues:
https://github.com/ray-project/kuberay/issues/2923
Testing Process:

[TPU Webhook] Fix KubeRay headless worker svc truncation bug

---

ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
ray-on-gke/tpu/kuberay-tpu-webhook/deployments/deployment.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/Chart.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/values.yaml

The `us-docker.pkg.dev/ai-on-gke/kuberay-tpu-webhook/tpu-webhook:v1.2.2-gke.1` image contains a bug fix for incorrect `TPU_WORKER_HOSTNAMES` caused by the KubeRay controller truncating the headless service name. This PR updates the default image used by the helm chart and deployments to the lastest correct version.

Update default TPU webhook image to v1.2.2

---

tutorials-and-examples/nvidia-nim/blueprints/README.md
tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/README.md
tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/nim-bionemo-generative-virtual-screening.yaml
tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/nim-storage-filestore.yaml
tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/test-generative-virtual-screening.py

Generative virtual screening for drug discovery NIM Blueprint on GKE

feat: nvidia nim blueprint for drug discovery

---

tutorials-and-examples/storage/parallelstore-backup-and-recovery/README.md
tutorials-and-examples/storage/parallelstore-backup-and-recovery/ps-to-gcs-backup.yaml
tutorials-and-examples/storage/parallelstore-backup-and-recovery/pstore-sa.yaml

Parallelstore currently only offered as a [“scratch storage” with MTTDL 2 to 16 month](https://cloud.google.com/parallelstore/docs/overview#performance). When the failure happened user might lose the data in their Parallelstore Instance.
This PR is to provide an example for mitigating this risk when using Parallelstore as storage, focusing on data backup and data recovery CUJ.

add user guide for parallelstore backup and recovery on GKE training workload

---

ray-on-gke/tpu/kuberay-tpu-webhook/main.go
ray-on-gke/tpu/kuberay-tpu-webhook/webhook_main_test.go

We should import the headless service suffix used by KubeRay when building the headless service used for multi-host TPU workers. Currently it's set as a constant in the webhook, which could lead to inconsistency if the value is changed in KubeRay.
This [PR](https://github.com/ray-project/kuberay/pull/3101) will shorten `HeadlessServiceSuffix` from `-headless-worker-svc` to just `-headless`, so we should submit this change first.

[TPU Webhook] Import headless service suffix from KubeRay

---

tutorials-and-examples/inference-servers/checkpoints/Dockerfile
tutorials-and-examples/inference-servers/checkpoints/README.md
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh

This PR adds the following changes/additions to the JetStream checkpoint converter: 
1. Support for quantization of maxtext models by invoking [the script](https://github.com/AI-Hypercomputer/maxtext/blob/main/MaxText/load_and_quantize_checkpoint.py) on maxtext repository.
2. Changes to the conversion scripts invoked (changed from `llama_ckpt_conversion_inference_only.py` to `llama_or_mistral_ckpt.py` and `generate_param_only_checkpoint.py`) as the former is not maintained by maxtext side
3. Updates script flags to be more verbose / easier to determine usage and intent.
4. Adds date and time to log outputs for debugging purposes.
The script has been tested e2e with Llama2-70b, Llama3.1-8b, Llama3.1-405b, and Llama3.3-70b.

Add quantization support for maxtext models and update conversion scripts

---

cloudbuild.yaml
security_test/config.yaml

The test fail of shipshape will cause the presubmit test fail.

Enable Shipshape secure by default

---

.github/workflows/stale.yaml

This workflow is to mark all issues as stale after 30 days, and mark for closure after 60. Issues labeled "awaiting-maintainer" will not be marked stale.

Create github workflow to mark old issues as stale and close

---

.github/workflows/obsolete.yaml

This GitHub workflow marks an issue as obsolete after 30 days of the "stale" label applied to the issue.

Marks issues as obsolete after 30 days of stale

---

.github/workflows/close.yaml

This GitHub workflow closes issues that have been labeled "obsolete" for 30 days. This means an issue is automatically closed after 90 days if it does not have the label "awaiting-maintainer".

Close obsolete issues after 30 days

---

applications/rag/frontend/main.tf
security_test/allowlist/category/cluster/rag-frontend/distroless.json
security_test/allowlist/category/cluster/rag-frontend/imagepath.json
security_test/allowlist/category/cluster/rag-frontend/sbom.json

Update the usage of rag frontend image to the version without complained vulnerabilities. The new image: https://pantheon.corp.google.com/artifacts/docker/ai-on-gke/us-central1/rag-on-gke/frontend/sha256:2b14a3a95f433cc394087ba0d6376d160d8080b62f485f1a119c52b8a6119368?e=13803378&mods=getting_started_solutions_mock_data&project=ai-on-gke
@blackzlq please verify my change to the allowlist makes sense

Update rag frontend image version

---

ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
ray-on-gke/tpu/kuberay-tpu-webhook/deployments/deployment.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/Chart.yaml
ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/values.yaml

This PR bumps the webhook image used in the deployment and helm-chart to the latest recommended version. The v1.2.3 webhook version contains fixes to the name of the TPU headless service generated by KubeRay.

Bump TPU Webhook to v1.2.3

---

tutorials-and-examples/inference-servers/checkpoints/README.md
tutorials-and-examples/inference-servers/checkpoints/checkpoint_converter.sh
tutorials-and-examples/inference-servers/checkpoints/examples/llama3.1-405b/README.md
tutorials-and-examples/inference-servers/checkpoints/examples/llama3.1-405b/checkpoint-converter.yaml

The checkpoint conversion script has been tested end-to-end with Llama3.1-405b, Llama2-70b, and other Llama variants. The checkpoints have been verified with MaxText-JetStream.

checkpoint conversion edits for guide and flag for increased byte i/o

---

modules/jupyter/jupyter_config/config-selfauth-autopilot.yaml
modules/jupyter/jupyter_config/config-selfauth.yaml
security_test/allowlist/category/cluster/hub/distroless.json
security_test/allowlist/category/cluster/hub/imagedigest.json
security_test/allowlist/category/cluster/hub/imagefreshness.json
security_test/allowlist/category/cluster/hub/imagepath.json

Add prefix `sample-public-image-` to the image tag to indicate image is not production ready.

Adds sample-public-image- prefix to jupyterhub-authentication-class/jupyter-auth-class image tag

---

tutorials-and-examples/workflow-orchestration/dws-examples/README.md
tutorials-and-examples/workflow-orchestration/dws-examples/job-autopilot.yaml

When running the example from the [documentation page](https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest) on GKE Autopilot cluster, when we reach the step to run `kubectl create -f ./job.yaml` I ended up with an error:
```
Error from server (GKE Warden constraints violations): error when creating "./job.yaml": admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: 
{
"[denied by autogke-gpu-limitation]":[
"When requesting 'nvidia.com/gpu' resources, you must specify either node selector 'cloud.google.com/gke-accelerator' with accelerator type or node selector 'cloud.google.com/compute-class' with existing custom compute class which …
```

fix(dws): Adding a job that's compatible with GKE autopilot

---

.github/pull_request_template.md
.github/workflows/label-pr.yaml

**What type of PR is this?**
/kind enhancement
**What this PR does / Why we need it**:
Creates a new [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to encourage structured pull requests on the repo.
Creates a GitHub workflow (based off of https://github.com/googleforgames/agones/blob/main/.github/workflows/label-pr.yml) to label a PR based on the kind defined in the pull request template.
**Which issue(s) this PR fixes**:
NA
**Special notes for your reviewer**:

Created new pull request template and auto labeler

---

applications/hcc/main.tf
applications/hcc/modules/embedded/modules/scheduler/gke-cluster/main.tf

- Added `maintenance_exclusions` to the `a3-megagpu-cluster` 
- Added the resource label `gke_product_type: cluster-director-qss` to identify the clusters provisioned by Cluster Director QSS

Configure maintenance exclusion and add cluster-director label 

---

applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/mega-test.yaml
applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/ultra-test.yaml
applications/hcc/modules/nemo/helm-charts/training/a3mega/nemo-training/templates/nemo-launcher-job.yaml
applications/hcc/modules/nemo/helm-charts/training/a3ultra/maxtext-training/templates/maxtext-launcher-job.yaml
applications/hcc/modules/nemo/helm-charts/training/a3ultra/nemo-training/templates/nemo-launcher-job.yaml
applications/hcc/modules/nemo/main.tf
applications/hcc/modules/nemo/recipe.tf

Adds identifying labels to the Pods created by the AI/ML workloads (Nemo, MaxText, NCCL tests) deployed via the Cluster Director Quick Start Solution.
The following labels are added to each workload pod's metadata:
* `ai-on-gke-solution`: Static value "cluster-director-qss"
* `ai-on-gke-machine-type`: Derived from GPU type (`a3mega` or `a3ultra`)
* `ai-on-gke-framework`: Derived from the selected recipe (`nemo`, `maxtext`, or `nccltest`)
* `ai-on-gke-model`: Derived from the selected recipe (e.g., `llama-3.1-7b`, `mixtral-8-7b`), omitted for NCCL tests.

Add identifying labels to workload pods

---

applications/hcc/metadata.display.yaml

updated a3ultra zones:
- europe-west1-b
- us-central1-b
- us-east4-b
- us-east5-a
- us-east7-c
- us-south1-b (new)
- us-west1-c

region update for a3ultra

---

applications/hcc/modules/nemo/main.tf
applications/hcc/modules/nemo/recipe.tf

- rename model label to be more generalized
- remove machine-type label
The following labels are added to each workload pod's metadata:
* `ai-on-gke-solution`: Static value "cluster-director-quick-start-solution"
* `ai-on-gke-framework`: Derived from the selected recipe (`nemo`, `maxtext`, or `nccltest`)
* `ai-on-gke-model`: Derived from the selected recipe (e.g., `llama`, `mixtral`), omitted for NCCL tests.

rename identifying labels to workload pods 
